/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

/**
 *
 * @author igeni
 */
public class BonosEInfracciones extends javax.swing.JPanel {

    /**
     * Creates new form BonosEInfracciones
     */
    public BonosEInfracciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jPanel2 = new javax.swing.JPanel();
        PEmpleados = new javax.swing.JPanel();
        LBLBusqEmpleado1 = new javax.swing.JLabel();
        TFFiltro = new javax.swing.JTextField();
        LBLBusqEmpleado2 = new javax.swing.JLabel();
        TFFiltro1 = new javax.swing.JTextField();
        LBLBusqEmpleado3 = new javax.swing.JLabel();
        BTNAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TEmpleados = new javax.swing.JTable();
        BTNEliEmpleado = new javax.swing.JButton();
        BTNModEmpleado = new javax.swing.JButton();
        LBLBusqEmpleado = new javax.swing.JLabel();
        PEmpleados1 = new javax.swing.JPanel();
        LBLBusqEmpleado4 = new javax.swing.JLabel();
        TFFiltro2 = new javax.swing.JTextField();
        LBLBusqEmpleado5 = new javax.swing.JLabel();
        TFFiltro3 = new javax.swing.JTextField();
        LBLBusqEmpleado6 = new javax.swing.JLabel();
        BTNAgregar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TEmpleados1 = new javax.swing.JTable();
        BTNEliEmpleado1 = new javax.swing.JButton();
        BTNModEmpleado1 = new javax.swing.JButton();

        panel1.setBackground(new java.awt.Color(36, 41, 46));

        jPanel2.setBackground(new java.awt.Color(36, 41, 46));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1871, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        PEmpleados.setBackground(new java.awt.Color(0, 51, 102));

        LBLBusqEmpleado1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLBusqEmpleado1.setForeground(new java.awt.Color(255, 255, 255));
        LBLBusqEmpleado1.setText("Porcentaje de disminución:");

        TFFiltro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFFiltroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFFiltroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFFiltroKeyTyped(evt);
            }
        });

        LBLBusqEmpleado2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLBusqEmpleado2.setForeground(new java.awt.Color(255, 255, 255));
        LBLBusqEmpleado2.setText("Nombre de la infracción o descuento:");

        TFFiltro1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFFiltro1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFFiltro1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFFiltro1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFFiltro1KeyTyped(evt);
            }
        });

        LBLBusqEmpleado3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLBusqEmpleado3.setForeground(new java.awt.Color(255, 255, 255));
        LBLBusqEmpleado3.setText("%");

        BTNAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agrega_empleado.png"))); // NOI18N
        BTNAgregar.setBorder(null);
        BTNAgregar.setBorderPainted(false);
        BTNAgregar.setContentAreaFilled(false);
        BTNAgregar.setFocusPainted(false);
        BTNAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNAgregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agrega_empleado2.png"))); // NOI18N
        BTNAgregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agrega_empleado1.png"))); // NOI18N
        BTNAgregar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTNAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAgregarActionPerformed(evt);
            }
        });

        TEmpleados = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        TEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Disminución"
            }
        ));
        TEmpleados.setFocusable(false);
        TEmpleados.getTableHeader().setReorderingAllowed(false);
        TEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TEmpleadosMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TEmpleadosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TEmpleados);

        BTNEliEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminarp.png"))); // NOI18N
        BTNEliEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliEmpleadoActionPerformed(evt);
            }
        });

        BTNModEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Modificarp.png"))); // NOI18N
        BTNModEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PEmpleadosLayout = new javax.swing.GroupLayout(PEmpleados);
        PEmpleados.setLayout(PEmpleadosLayout);
        PEmpleadosLayout.setHorizontalGroup(
            PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PEmpleadosLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLBusqEmpleado2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PEmpleadosLayout.createSequentialGroup()
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLBusqEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PEmpleadosLayout.createSequentialGroup()
                                .addComponent(TFFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LBLBusqEmpleado3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BTNAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PEmpleadosLayout.createSequentialGroup()
                                .addComponent(BTNEliEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTNModEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        PEmpleadosLayout.setVerticalGroup(
            PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PEmpleadosLayout.createSequentialGroup()
                .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PEmpleadosLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(LBLBusqEmpleado2)
                        .addGap(18, 18, 18)
                        .addComponent(TFFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LBLBusqEmpleado1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLBusqEmpleado3))
                        .addGap(18, 18, 18)
                        .addComponent(BTNAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PEmpleadosLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTNEliEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNModEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LBLBusqEmpleado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLBusqEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        LBLBusqEmpleado.setText("Ingreso de bonos y descuentos:");

        PEmpleados1.setBackground(new java.awt.Color(0, 51, 102));

        LBLBusqEmpleado4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLBusqEmpleado4.setForeground(new java.awt.Color(255, 255, 255));
        LBLBusqEmpleado4.setText("Porcentaje de aumento:");

        TFFiltro2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFFiltro2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFFiltro2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFFiltro2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFFiltro2KeyTyped(evt);
            }
        });

        LBLBusqEmpleado5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLBusqEmpleado5.setForeground(new java.awt.Color(255, 255, 255));
        LBLBusqEmpleado5.setText("Nombre del bono:");

        TFFiltro3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFFiltro3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFFiltro3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFFiltro3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFFiltro3KeyTyped(evt);
            }
        });

        LBLBusqEmpleado6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLBusqEmpleado6.setForeground(new java.awt.Color(255, 255, 255));
        LBLBusqEmpleado6.setText("%");

        BTNAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agrega_empleado.png"))); // NOI18N
        BTNAgregar1.setBorder(null);
        BTNAgregar1.setBorderPainted(false);
        BTNAgregar1.setContentAreaFilled(false);
        BTNAgregar1.setFocusPainted(false);
        BTNAgregar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNAgregar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agrega_empleado2.png"))); // NOI18N
        BTNAgregar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agrega_empleado1.png"))); // NOI18N
        BTNAgregar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTNAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAgregar1ActionPerformed(evt);
            }
        });

        TEmpleados = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        TEmpleados1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Aumento"
            }
        ));
        TEmpleados1.setFocusable(false);
        TEmpleados1.getTableHeader().setReorderingAllowed(false);
        TEmpleados1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TEmpleados1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TEmpleados1MouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(TEmpleados1);

        BTNEliEmpleado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminarp.png"))); // NOI18N
        BTNEliEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliEmpleado1ActionPerformed(evt);
            }
        });

        BTNModEmpleado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Modificarp.png"))); // NOI18N
        BTNModEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModEmpleado1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PEmpleados1Layout = new javax.swing.GroupLayout(PEmpleados1);
        PEmpleados1.setLayout(PEmpleados1Layout);
        PEmpleados1Layout.setHorizontalGroup(
            PEmpleados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PEmpleados1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(PEmpleados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLBusqEmpleado5, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PEmpleados1Layout.createSequentialGroup()
                        .addGroup(PEmpleados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFFiltro2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLBusqEmpleado4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PEmpleados1Layout.createSequentialGroup()
                                .addComponent(TFFiltro3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LBLBusqEmpleado6, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BTNAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PEmpleados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PEmpleados1Layout.createSequentialGroup()
                                .addComponent(BTNEliEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTNModEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        PEmpleados1Layout.setVerticalGroup(
            PEmpleados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PEmpleados1Layout.createSequentialGroup()
                .addGroup(PEmpleados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PEmpleados1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(LBLBusqEmpleado5)
                        .addGap(18, 18, 18)
                        .addComponent(TFFiltro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LBLBusqEmpleado4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PEmpleados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFFiltro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLBusqEmpleado6))
                        .addGap(18, 18, 18)
                        .addComponent(BTNAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PEmpleados1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(PEmpleados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BTNEliEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNModEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(LBLBusqEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(PEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1930, 1930, 1930)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel1Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(PEmpleados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(3806, Short.MAX_VALUE)))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(328, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LBLBusqEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel1Layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(PEmpleados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(360, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TFFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltroKeyPressed

    }//GEN-LAST:event_TFFiltroKeyPressed

    private void TFFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltroKeyReleased
        //while(empleados.getRowCount()>0)
        //empleados.removeRow(0);
        //while(clientes.getRowCount()>0)
        //clientes.removeRow(0);
        //if (!TFFiltro.getText().equals(""))
        //Insercion.Filtro(empleados, TFFiltro.getText());
        //else
        //Insercion.Buscar(empleados);
    }//GEN-LAST:event_TFFiltroKeyReleased

    private void TFFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltroKeyTyped
        char c = evt.getKeyChar();

        if ((c<'a' || c>'z') && (c<'A')|c>'Z') evt.consume();
        if (TFFiltro.getText().length() > 30) evt.consume();

    }//GEN-LAST:event_TFFiltroKeyTyped

    private void TFFiltro1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltro1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFFiltro1KeyPressed

    private void TFFiltro1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltro1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TFFiltro1KeyReleased

    private void TFFiltro1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltro1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TFFiltro1KeyTyped

    private void BTNAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAgregarActionPerformed
        //AgregarEmpleado();
    }//GEN-LAST:event_BTNAgregarActionPerformed

    private void TEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TEmpleadosMouseClicked

    }//GEN-LAST:event_TEmpleadosMouseClicked

    private void TEmpleadosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TEmpleadosMouseReleased
        //contemp = idseleccionado;
        //SeleccionarEmpleado();
        /*if (contemp == idseleccionado)
        clickemp ++;
        else
        clickemp = 0;
        if (clickemp == 3)
        {
            EliminarEmpleado();
            clickemp = 0;
        }*/
    }//GEN-LAST:event_TEmpleadosMouseReleased

    private void BTNEliEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEliEmpleadoActionPerformed
        //EliminarEmpleado();
    }//GEN-LAST:event_BTNEliEmpleadoActionPerformed

    private void BTNModEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModEmpleadoActionPerformed
        //ModificarEmpleado();
    }//GEN-LAST:event_BTNModEmpleadoActionPerformed

    private void TFFiltro2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltro2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFFiltro2KeyPressed

    private void TFFiltro2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltro2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TFFiltro2KeyReleased

    private void TFFiltro2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltro2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TFFiltro2KeyTyped

    private void TFFiltro3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltro3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFFiltro3KeyPressed

    private void TFFiltro3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltro3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TFFiltro3KeyReleased

    private void TFFiltro3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltro3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TFFiltro3KeyTyped

    private void BTNAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAgregar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNAgregar1ActionPerformed

    private void TEmpleados1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TEmpleados1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TEmpleados1MouseClicked

    private void TEmpleados1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TEmpleados1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TEmpleados1MouseReleased

    private void BTNEliEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEliEmpleado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNEliEmpleado1ActionPerformed

    private void BTNModEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModEmpleado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNModEmpleado1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAgregar;
    private javax.swing.JButton BTNAgregar1;
    private javax.swing.JButton BTNEliEmpleado;
    private javax.swing.JButton BTNEliEmpleado1;
    private javax.swing.JButton BTNModEmpleado;
    private javax.swing.JButton BTNModEmpleado1;
    private javax.swing.JLabel LBLBusqEmpleado;
    private javax.swing.JLabel LBLBusqEmpleado1;
    private javax.swing.JLabel LBLBusqEmpleado2;
    private javax.swing.JLabel LBLBusqEmpleado3;
    private javax.swing.JLabel LBLBusqEmpleado4;
    private javax.swing.JLabel LBLBusqEmpleado5;
    private javax.swing.JLabel LBLBusqEmpleado6;
    private javax.swing.JPanel PEmpleados;
    private javax.swing.JPanel PEmpleados1;
    private javax.swing.JTable TEmpleados;
    private javax.swing.JTable TEmpleados1;
    private javax.swing.JTextField TFFiltro;
    private javax.swing.JTextField TFFiltro1;
    private javax.swing.JTextField TFFiltro2;
    private javax.swing.JTextField TFFiltro3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
