/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import compras.ComprasEmpresas;
import compras.DetallesCompraEmpresas;
import entidades.Compra;
import entidades.Compras;
import entidades.Detallecompras;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import singleton.singleton;

/**
 *
 * @author User
 */
public class ComprarEmpresas extends javax.swing.JPanel {

    Compras empresa;//Variable que obtiene los datos de la empresa traspasada desde el otro form
    //Se asigna el modelo a la tabla de detalles de la factura de compra a generar
    public ComprarEmpresas(Compras empresa) {
        this.empresa = empresa;
        initComponents();
        lblEmpresa.setText("Efectuar compra a: " + empresa.getEmpresa());
        DefaultTableModel modeloDetalles = new DefaultTableModel();
        tCompras.setModel(modeloDetalles);
        modeloDetalles.addColumn("Cantidad");
        modeloDetalles.addColumn("Descripción");
        modeloDetalles.addColumn("Sub-total");
        tfCantidad.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        lblEmpresa = new javax.swing.JLabel();
        tfCantidad = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        lblCantidad1 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        tfDescripcion = new javax.swing.JTextField();
        tfSubTotal = new javax.swing.JTextField();
        jScrollPabe1 = new javax.swing.JScrollPane();
        tCompras = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(36, 41, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        btnRegresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back2.png"))); // NOI18N
        btnRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back1.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        lblEmpresa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpresa.setText("Efectuar compra a:");
        jPanel1.add(lblEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 600, -1));

        tfCantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCantidadKeyTyped(evt);
            }
        });
        jPanel1.add(tfCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 120, -1));

        lblCantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad.setText("Cantidad:");
        jPanel1.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, -1));

        lblCantidad1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCantidad1.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad1.setText("Descripción:");
        jPanel1.add(lblCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 120, -1));

        lblSubTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblSubTotal.setText("Sub-total (c/u):");
        jPanel1.add(lblSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 130, -1));

        tfDescripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDescripcionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDescripcionKeyTyped(evt);
            }
        });
        jPanel1.add(tfDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 340, -1));

        tfSubTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfSubTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSubTotalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSubTotalKeyTyped(evt);
            }
        });
        jPanel1.add(tfSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 120, -1));

        tCompras = new javax.swing.JTable(){ public boolean isCellEditable(int rowIndex, int colIndex){     return false;     } };
        tCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tCompras.setFocusable(false);
        tCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tComprasMouseReleased(evt);
            }
        });
        jScrollPabe1.setViewportView(tCompras);

        jPanel1.add(jScrollPabe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 649, 250));

        btnAgregar.setBackground(new java.awt.Color(0, 136, 204));
        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, -1, -1));

        btnIngresar.setBackground(new java.awt.Color(0, 136, 204));
        btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 200, 80));

        btnEliminar.setBackground(new java.awt.Color(0, 136, 204));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("X");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    //Regresar al form de compras
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FormCompras compras = new FormCompras();
        compras.setSize(1010,600);
        compras.setLocation(0, 0);
        this.removeAll();
        this.add(compras,BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnRegresarActionPerformed
    //Validación de hacer enter a cantidad, que haga focus al textfield de descripción
    private void tfCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCantidadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            tfDescripcion.requestFocus();
    }//GEN-LAST:event_tfCantidadKeyPressed
    //Validación de los dígitos (también validados) ingresados, a un máximo de 6
    private void tfCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCantidadKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
        if (tfCantidad.getText().length() == 0 && c == '0')
            evt.consume();
        if (tfCantidad.getText().length() > 6) evt.consume();
    }//GEN-LAST:event_tfCantidadKeyTyped
    //Validación de hacer enter, para que haga focus al textfield de subtotal
    private void tfDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDescripcionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            tfSubTotal.requestFocus();
    }//GEN-LAST:event_tfDescripcionKeyPressed
    //Validación de un máximo de 100 caracteres en descripción
    private void tfDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDescripcionKeyTyped
        if (tfCantidad.getText().length() > 100) evt.consume();
    }//GEN-LAST:event_tfDescripcionKeyTyped

    private void tfSubTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSubTotalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) agregarDetalle();
    }//GEN-LAST:event_tfSubTotalKeyPressed
    //Validación de un máximo de 7 caracteres (validados) 
    private void tfSubTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSubTotalKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
        {
            if (c != '.')
                evt.consume();
        }
        if (tfSubTotal.getText().length() > 7) evt.consume();
    }//GEN-LAST:event_tfSubTotalKeyTyped

    private void tComprasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tComprasMouseReleased

    }//GEN-LAST:event_tComprasMouseReleased
    //Agregar detalle a la factura de compra
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregarDetalle();
    }//GEN-LAST:event_btnAgregarActionPerformed
    private void agregarDetalle()
    {
        if (tfCantidad.getText().length() > 0 && tfDescripcion.getText().length() > 0 && tfSubTotal.getText().length() > 0)
        {
            Object O[] = null;
            DefaultTableModel modeloCompras = (DefaultTableModel)tCompras.getModel();
            modeloCompras.addRow(O);
            int cantidad = Integer.parseInt(tfCantidad.getText());
            float subtotal = cantidad * Float.parseFloat(tfSubTotal.getText());
            modeloCompras.setValueAt(cantidad, modeloCompras.getRowCount()-1 , 0);
            modeloCompras.setValueAt(tfDescripcion.getText(), modeloCompras.getRowCount()-1 , 1);
            modeloCompras.setValueAt(subtotal, modeloCompras.getRowCount()-1 , 2);
            tfCantidad.setText("");
            tfDescripcion.setText("");
            tfSubTotal.setText("");
            tfCantidad.requestFocus();
        }
        else
            JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos disponibles");
    }


    //Crear factura de compra y sus detalles
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        DefaultTableModel modeloCompras = (DefaultTableModel) tCompras.getModel();
        float total = totalCompra();
        if (modeloCompras.getRowCount() > 0) {
            tfCantidad.setText("");
            tfDescripcion.setText("");
            tfSubTotal.setText("");
            if (JOptionPane.showConfirmDialog(null, "¿Efectuar Compra?", "Aviso",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                ComprasEmpresas generarcompra = new ComprasEmpresas();
                DetallesCompraEmpresas generardetalles = new DetallesCompraEmpresas();
                LocalDateTime horayfechaActual = LocalDateTime.now();
                DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
                Compra compra = new Compra();
                compra.setFechaHora(Date.from(horayfechaActual.atZone(ZoneId.systemDefault()).toInstant()));
                compra.setTotal(total);
                compra.setComprasIdcompras(empresa);
                generarcompra.registrarObject(compra, singleton.getConnection());
                for (int i = 0; i < modeloCompras.getRowCount(); i++) {
                    Detallecompras detalle = new Detallecompras();
                    detalle.setCantidad(Integer.parseInt(String.valueOf(tCompras.getValueAt(i, 0))));
                    detalle.setMonto(Float.parseFloat(String.valueOf(tCompras.getValueAt(i, 2))));
                    detalle.setCompraid(compra);
                    detalle.setDescripcion(String.valueOf(tCompras.getValueAt(i, 1)));
                    generardetalles.registrarObject(detalle, singleton.getConnection());
                }
            }
            while (modeloCompras.getRowCount() > 0) {
                modeloCompras.removeRow(0);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay ningún detalle por agregar en la compra");
        }
    }//GEN-LAST:event_btnIngresarActionPerformed
    //Calcular el total de la compra
    private float totalCompra()
    {
        float total = 0;
        for (int i = 0; i < tCompras.getRowCount(); i++)
            total += Float.parseFloat(String.valueOf(tCompras.getValueAt(i, 2)));
        return total;
    }
    //Eliminar detalles no deseados antes de crear la factura de compra
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        DefaultTableModel modeloCompras = (DefaultTableModel) tCompras.getModel();
        if (tCompras.getSelectedRow() > -1)
            modeloCompras.removeRow(tCompras.getSelectedRow());
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPabe1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCantidad1;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JTable tCompras;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfSubTotal;
    // End of variables declaration//GEN-END:variables
}
