/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import recursoshumanos.Contrasena;
import recursoshumanos.ClaseEmpleados;
import entidades.Empleados;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import singleton.singleton;

/**
 *
 * @author User
 */
public class CreacionUsuarios extends javax.swing.JFrame {

    Empleados empleado;//Se obtiene los datos del empleado, gracias al traspaso del mismo en el form del login
    ClaseEmpleados clasEmpleados = new ClaseEmpleados();//Variable para efectuar la adición de datos al empleado
    Contrasena contrasena = new Contrasena();//Variable para encriptar la contraseña ingresada
    //Centrar form, y hacer focus al textfield de usuario
    public CreacionUsuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        tfUsuario.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRespuesta = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        tfRespuesta = new javax.swing.JTextField();
        pfConfirmarContra = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblContrasena = new javax.swing.JLabel();
        pfContrasena = new javax.swing.JPasswordField();
        btnAgregar = new javax.swing.JButton();
        lblPreguntas = new javax.swing.JLabel();
        rbDeporte = new javax.swing.JRadioButton();
        rbMejorAmigo = new javax.swing.JRadioButton();
        rbMascota = new javax.swing.JRadioButton();
        lblUsuario = new javax.swing.JLabel();
        lblConfirmarContra = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(36, 41, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRespuesta.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        lblRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        lblRespuesta.setText("Respuesta:");
        jPanel1.add(lblRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        lblEmpleado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpleado.setText("Empleado:");
        jPanel1.add(lblEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        tfRespuesta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfRespuesta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfRespuestaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfRespuestaKeyTyped(evt);
            }
        });
        jPanel1.add(tfRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 210, -1));

        pfConfirmarContra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pfConfirmarContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfConfirmarContraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pfConfirmarContraKeyTyped(evt);
            }
        });
        jPanel1.add(pfConfirmarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 210, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida2.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida3.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida1.png"))); // NOI18N
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimiza2.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimizar3.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimizar1.png"))); // NOI18N
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, -1, -1));

        lblContrasena.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasena.setText("Contraseña:");
        jPanel1.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        pfContrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pfContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfContrasenaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pfContrasenaKeyTyped(evt);
            }
        });
        jPanel1.add(pfContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 210, -1));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agre1.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 110, 40));

        lblPreguntas.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        lblPreguntas.setForeground(new java.awt.Color(255, 255, 255));
        lblPreguntas.setText("Preguntas de respaldo:");
        jPanel1.add(lblPreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        rbDeporte.setBackground(new java.awt.Color(36, 41, 46));
        rbDeporte.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbDeporte.setForeground(new java.awt.Color(255, 255, 255));
        rbDeporte.setText("Mi deporte favorito es:");
        rbDeporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDeporteActionPerformed(evt);
            }
        });
        rbDeporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbDeporteKeyPressed(evt);
            }
        });
        jPanel1.add(rbDeporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));

        rbMejorAmigo.setBackground(new java.awt.Color(36, 41, 46));
        rbMejorAmigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbMejorAmigo.setForeground(new java.awt.Color(255, 255, 255));
        rbMejorAmigo.setText("Conocí a mi mejor amigo en la ciudad de:");
        rbMejorAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMejorAmigoActionPerformed(evt);
            }
        });
        rbMejorAmigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbMejorAmigoKeyPressed(evt);
            }
        });
        jPanel1.add(rbMejorAmigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));

        rbMascota.setBackground(new java.awt.Color(36, 41, 46));
        rbMascota.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbMascota.setForeground(new java.awt.Color(255, 255, 255));
        rbMascota.setText("Mi mascota preferida es:");
        rbMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMascotaActionPerformed(evt);
            }
        });
        rbMascota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbMascotaKeyPressed(evt);
            }
        });
        jPanel1.add(rbMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario:");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        lblConfirmarContra.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        lblConfirmarContra.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmarContra.setText("Confirmar contraseña:");
        jPanel1.add(lblConfirmarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        tfUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(tfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 210, -1));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        btnRegresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back2.png"))); // NOI18N
        btnRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back1.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Validación de movimiento entre textfields
    private void tfRespuestaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRespuestaKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_DOWN) tfUsuario.requestFocus();
        else if (evt.getKeyCode()==KeyEvent.VK_UP) rbMejorAmigo.requestFocus();
    }//GEN-LAST:event_tfRespuestaKeyPressed
    //Validación de un máximo de 60 caracteres en el campo de respuesta
    private void tfRespuestaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRespuestaKeyTyped
        if (tfRespuesta.getText().length() > 60) evt.consume();
    }//GEN-LAST:event_tfRespuestaKeyTyped
    //Validación de movimiento entre textfields
    private void pfConfirmarContraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfConfirmarContraKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) tfRespuesta.requestFocus();
        else if (evt.getKeyCode()==KeyEvent.VK_DOWN) rbMascota.requestFocus();
        else if (evt.getKeyCode()==KeyEvent.VK_UP) pfContrasena.requestFocus();
    }//GEN-LAST:event_pfConfirmarContraKeyPressed
    //Validación de un máximo de 25 caracteres en el campo de confirmación de contraseña
    private void pfConfirmarContraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfConfirmarContraKeyTyped
        if (pfConfirmarContra.getPassword().length > 25) evt.consume();
    }//GEN-LAST:event_pfConfirmarContraKeyTyped
    //Preguntar si se quiere salir del sistema
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int sino = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(null,"¿Desea Salir del Sistema?","Exit",sino);
        if(resultado==0){

            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setState(CreacionUsuarios.ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed
    //Validación de movimiento entre textfields
    private void pfContrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfContrasenaKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) pfConfirmarContra.requestFocus();
        else if (evt.getKeyCode()==KeyEvent.VK_DOWN) pfConfirmarContra.requestFocus();
        else if (evt.getKeyCode()==KeyEvent.VK_UP) tfUsuario.requestFocus();
    }//GEN-LAST:event_pfContrasenaKeyPressed
    //Validación de un máximo de 25 caracteres en el campo de contraseña
    private void pfContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfContrasenaKeyTyped
        if (pfContrasena.getPassword().length > 25) evt.consume();
    }//GEN-LAST:event_pfContrasenaKeyTyped
    //Validación de que sólo el radiobutton de deporte esté accionado
    private void rbDeporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDeporteActionPerformed
        if (rbDeporte.isSelected())
        {
            rbMascota.setSelected(false);
            rbMejorAmigo.setSelected(false);
        }
        if (!rbDeporte.isSelected())
            rbDeporte.setSelected(true);
    }//GEN-LAST:event_rbDeporteActionPerformed
    //Validación de que sólo el radiobutton de mejor amigo esté accionado
    private void rbMejorAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMejorAmigoActionPerformed
        if (rbMejorAmigo.isSelected())
        {
            rbMascota.setSelected(false);
            rbDeporte.setSelected(false);
        }
        if (!rbMejorAmigo.isSelected())
            rbMejorAmigo.setSelected(false);
    }//GEN-LAST:event_rbMejorAmigoActionPerformed
    //Validación de que sólo el radiobutton de mascota esté accionado
    private void rbMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMascotaActionPerformed
        if (rbMascota.isSelected())
        {
            rbDeporte.setSelected(false);
            rbMejorAmigo.setSelected(false);
        }
        if (!rbMascota.isSelected())
            rbMascota.setSelected(true);
    }//GEN-LAST:event_rbMascotaActionPerformed
    //Validación de movimiento entre textfields
    private void tfUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUsuarioKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) pfContrasena.requestFocus();
        else if (evt.getKeyCode()==KeyEvent.VK_DOWN) pfContrasena.requestFocus();
        else if (evt.getKeyCode()==KeyEvent.VK_UP) tfRespuesta.requestFocus();
    }//GEN-LAST:event_tfUsuarioKeyPressed
    //Validación de un máximo de 25 caracteres para ingresar el usuario
    private void tfUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUsuarioKeyTyped
        if (tfUsuario.getText().length() > 25) evt.consume();
    }//GEN-LAST:event_tfUsuarioKeyTyped
    //Traspaso de variable de tipo empleado entre el form login y de creación de usuarios
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lblEmpleado.setText("Empleado: " + empleado.getNombre() + " " + empleado.getApellido());
    }//GEN-LAST:event_formWindowActivated
    //Añadir usuario y contraseña
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (!tfUsuario.equals("") && !pfContrasena.equals("") && !pfConfirmarContra.equals("") && !tfRespuesta.equals("")
                && (rbMascota.isSelected() || rbDeporte.isSelected() || rbMejorAmigo.isSelected()))
        {
            if (!String.valueOf(pfContrasena.getPassword()).equals(String.valueOf(pfConfirmarContra.getPassword())))
                JOptionPane.showMessageDialog(null, "Las contraseñas ingresadas no coinciden");
            else
            {
                if (clasEmpleados.buscarUsuario(singleton.getConnection(), tfUsuario.getText()) == null)
                {
                    empleado.setUsuario(tfUsuario.getText());
                    empleado.setContrasena(contrasena.Encriptar(String.valueOf(pfContrasena.getPassword())));
                    if (rbMascota.isSelected())
                        empleado.setPregunta(rbMascota.getText());
                    else if (rbDeporte.isSelected())
                        empleado.setPregunta(rbDeporte.getText());
                    else if (rbMejorAmigo.isSelected())
                        empleado.setPregunta(rbMejorAmigo.getText());
                    empleado.setRespuesta(tfRespuesta.getText());
                    clasEmpleados.editarObject(empleado, singleton.getConnection(), empleado.getId());
                    JOptionPane.showMessageDialog(null, "Usuario generado exitósamente");
                    JOptionPane.showMessageDialog(null, "Por favor proceda a autentificarse nuevamente en el login");
                    Login login = new Login();
                    login.setVisible(true);
                    this.setVisible(false);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "El usuario especificado ya existe");
                    tfUsuario.setText("");
                }
                    
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos solicitados");
    }//GEN-LAST:event_btnAgregarActionPerformed
    //Validación de movimiento entre radiobuttons
    private void rbMascotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbMascotaKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_DOWN) rbDeporte.requestFocus();
        else if (evt.getKeyCode()==KeyEvent.VK_UP) pfConfirmarContra.requestFocus();
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) 
        {
            rbMascota.setSelected(true);
            rbDeporte.setSelected(false);
            rbMejorAmigo.setSelected(false);
        }
    }//GEN-LAST:event_rbMascotaKeyPressed
    //Validación de movimiento entre radiobuttons
    private void rbDeporteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbDeporteKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_DOWN) rbMejorAmigo.requestFocus();
        else if (evt.getKeyCode()==KeyEvent.VK_UP) rbMascota.requestFocus();
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) 
        {
            rbMascota.setSelected(false);
            rbDeporte.setSelected(true);
            rbMejorAmigo.setSelected(false);
        }
    }//GEN-LAST:event_rbDeporteKeyPressed
    //Validación de movimiento entre radiobuttons
    private void rbMejorAmigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbMejorAmigoKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_DOWN) tfRespuesta.requestFocus();
        else if (evt.getKeyCode()==KeyEvent.VK_UP) rbDeporte.requestFocus();
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) 
        {
            rbMascota.setSelected(false);
            rbDeporte.setSelected(false);
            rbMejorAmigo.setSelected(true);
        }
    }//GEN-LAST:event_rbMejorAmigoKeyPressed
    //Regresar al login y no guardar los cambios efectuados
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreacionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreacionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreacionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreacionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreacionUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfirmarContra;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblPreguntas;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField pfConfirmarContra;
    private javax.swing.JPasswordField pfContrasena;
    private javax.swing.JRadioButton rbDeporte;
    private javax.swing.JRadioButton rbMascota;
    private javax.swing.JRadioButton rbMejorAmigo;
    private javax.swing.JTextField tfRespuesta;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
