/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import controladores.ProductoJpaController;
import java.awt.Color;
import entidades.*;
import inventario.Inventario;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import singleton.singleton;


/**
 *
 * @author felipe
 */
public class finvenario extends javax.swing.JPanel {

    /**
     * Creates new form finvenario
     */
    private boolean  actualizar;
    private Producto producto;
    Inventario inventario;
    public finvenario() {
        initComponents();
        inventario = new Inventario();
        cbCategoria.setModel(inventario.listCategoria(1, singleton.getConnection()));
        actualizar = false;
        TablaProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        categoria = new javax.swing.JTabbedPane();
        pnProducto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomProducto = new javax.swing.JTextField();
        txtCanProducto = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtPrecioProducto = new javax.swing.JTextField();

        jTextField3.setText("jTextField3");

        setBackground(new java.awt.Color(36, 41, 46));

        pnProducto.setBackground(new java.awt.Color(36, 41, 46));
        pnProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(36, 41, 46));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccionar categoria:");
        pnProducto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 37, -1, -1));

        cbCategoria.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbCategoria.setForeground(new java.awt.Color(255, 255, 255));
        cbCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCategoriaMouseClicked(evt);
            }
        });
        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaActionPerformed(evt);
            }
        });
        pnProducto.add(cbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 36, 215, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inserción de producto.");
        pnProducto.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 87, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        pnProducto.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 125, -1, -1));

        jLabel4.setBackground(new java.awt.Color(36, 41, 46));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad:");
        pnProducto.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 125, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio venta:");
        pnProducto.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 125, -1, -1));

        txtNomProducto.setBackground(new java.awt.Color(36, 41, 46));
        txtNomProducto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNomProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtNomProducto.setBorder(null);
        pnProducto.add(txtNomProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 120, 220, 30));

        txtCanProducto.setBackground(new java.awt.Color(36, 41, 46));
        txtCanProducto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCanProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtCanProducto.setBorder(null);
        pnProducto.add(txtCanProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 100, 30));

        btnAceptar.setBackground(new java.awt.Color(0, 136, 204));
        btnAceptar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(null);
        btnAceptar.setFocusPainted(false);
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAceptarMouseExited(evt);
            }
        });
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        pnProducto.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, -1, 47));

        tbProductos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        tbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbProductosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbProductos);

        pnProducto.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 236, 835, 327));
        pnProducto.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 153, 220, 5));
        pnProducto.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 153, 100, 10));
        pnProducto.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 153, 100, 5));

        txtPrecioProducto.setBackground(new java.awt.Color(36, 41, 46));
        txtPrecioProducto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPrecioProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecioProducto.setBorder(null);
        pnProducto.add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 100, 30));

        categoria.addTab("Producto", pnProducto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(categoria)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(categoria)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbProductosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbProductosKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            DefaultTableModel model = (DefaultTableModel)tbProductos.getModel();
            JOptionPane.showMessageDialog(null, "Actu "+model.getValueAt(tbProductos.getSelectedRow(), 2));
        }
    }//GEN-LAST:event_tbProductosKeyPressed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:

        if( !txtCanProducto.getText().equals("") &&
            !txtNomProducto.getText().equals("") &&
            !txtPrecioProducto.getText().equals("")){

            if(!actualizar){

                Producto producto1 = new Producto(0,(cbCategoria.getSelectedIndex()+1));
                producto1.setNombre(txtNomProducto.getText());
                producto1.setCantidad(Integer.parseInt(txtCanProducto.getText()));
                producto1.setPrecioVenta(Float.parseFloat(txtPrecioProducto.getText()));

                try {

                    if(inventario.registrarObject(producto1,singleton.getConnection()))
                    JOptionPane.showMessageDialog(null, "Producto insertado");

                    limpiearTextbox();
                    tbProductos.setModel(inventario.listProducto(cbCategoria.getSelectedIndex()+1,singleton.getConnection()));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Fallo en la insercion");
                }
            }else{
                try {
                    EntityManager em = singleton.getConnection();
                    ProductoJpaController controller = new ProductoJpaController(em);
                    producto.setNombre(txtNomProducto.getText());
                    producto.setCantidad(Integer.parseInt(txtCanProducto.getText()));
                    producto.setPrecioVenta(Float.parseFloat(txtPrecioProducto.getText()));
                    controller.edit(producto);

                    tbProductos.setModel(inventario.listProducto(cbCategoria.getSelectedIndex()+1,em));
                    em.close();
                    actualizar = false;
                    btnAceptar.setText("Aceptar");
                    limpiearTextbox();
                    JOptionPane.showMessageDialog(null, "Producto modificado");

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Falla en la modificacion");
                }
            }

        }
        else
        JOptionPane.showMessageDialog(null, "Favor de llenar todos los campos");
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseExited
        // TODO add your handling code here:
        btnAceptar.setBackground(new Color(0,136,204));
    }//GEN-LAST:event_btnAceptarMouseExited

    private void btnAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseEntered
        // TODO add your handling code here:
        btnAceptar.setBackground(Color.red);
    }//GEN-LAST:event_btnAceptarMouseEntered

    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
        // TODO add your handling code here:
        tbProductos.setModel(inventario.listProducto(cbCategoria.getSelectedIndex()+1,singleton.getConnection()));
    }//GEN-LAST:event_cbCategoriaActionPerformed

    private void cbCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCategoriaMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbCategoriaMouseClicked

        //Funcion para dar doble click sobre el jtable producto
    private void TablaProductos(){
     tbProductos.addMouseListener(new MouseAdapter() {
           @Override
            public void mouseClicked(MouseEvent e){
           
              if(e.getClickCount() == 2){
                producto = inventario.getProducto(tbProductos.getSelectedRow());
                txtNomProducto.setText(producto.getNombre());
                txtCanProducto.setText(producto.getCantidad()+"");
                txtPrecioProducto.setText(producto.getPrecioVenta()+"");
                actualizar = true;
                btnAceptar.setText("Actualizar");
              }
          }
        });
    }    
    private void limpiearTextbox(){
      txtCanProducto.setText("");
      txtNomProducto.setText("");
      txtPrecioProducto.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JTabbedPane categoria;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel pnProducto;
    private javax.swing.JTable tbProductos;
    private javax.swing.JTextField txtCanProducto;
    private javax.swing.JTextField txtNomProducto;
    private javax.swing.JTextField txtPrecioProducto;
    // End of variables declaration//GEN-END:variables
}
