/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.awt.Color;
import entidades.*;
import javax.swing.JOptionPane;
import singleton.singleton;

/**
 *
 * @author felipe
 */
public class Finvenario extends javax.swing.JPanel {

    /**
     * Creates new form finvenario
     */
    public Finvenario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        categoria = new javax.swing.JTabbedPane();
        pnProducto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomProducto = new javax.swing.JTextField();
        txtCanProducto = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtPrecioProducto = new javax.swing.JTextField();
        pnCategoria = new javax.swing.JPanel();

        jTextField3.setText("jTextField3");

        setBackground(new java.awt.Color(36, 41, 46));

        pnProducto.setBackground(new java.awt.Color(36, 41, 46));
        pnProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(36, 41, 46));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccionar categoria:");
        pnProducto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 37, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        pnProducto.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 36, 215, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inserción de producto.");
        pnProducto.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 87, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        pnProducto.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 125, -1, -1));

        jLabel4.setBackground(new java.awt.Color(36, 41, 46));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad:");
        pnProducto.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 125, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio venta:");
        pnProducto.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 125, -1, -1));

        txtNomProducto.setBackground(new java.awt.Color(36, 41, 46));
        txtNomProducto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNomProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtNomProducto.setBorder(null);
        pnProducto.add(txtNomProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 120, 220, 30));

        txtCanProducto.setBackground(new java.awt.Color(36, 41, 46));
        txtCanProducto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCanProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtCanProducto.setBorder(null);
        pnProducto.add(txtCanProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 100, 30));

        btnAceptar.setBackground(new java.awt.Color(0, 136, 204));
        btnAceptar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(null);
        btnAceptar.setFocusPainted(false);
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAceptarMouseExited(evt);
            }
        });
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        pnProducto.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, -1, 47));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pnProducto.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 236, 835, 327));
        pnProducto.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 153, 220, 5));
        pnProducto.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 153, 100, 10));
        pnProducto.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 153, 100, 5));

        txtPrecioProducto.setBackground(new java.awt.Color(36, 41, 46));
        txtPrecioProducto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPrecioProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecioProducto.setBorder(null);
        pnProducto.add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 100, 30));

        categoria.addTab("Producto", pnProducto);

        pnCategoria.setBackground(new java.awt.Color(36, 41, 46));

        javax.swing.GroupLayout pnCategoriaLayout = new javax.swing.GroupLayout(pnCategoria);
        pnCategoria.setLayout(pnCategoriaLayout);
        pnCategoriaLayout.setHorizontalGroup(
            pnCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        pnCategoriaLayout.setVerticalGroup(
            pnCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        categoria.addTab("Categoria", pnCategoria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(categoria)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(categoria)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
       
        
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseEntered
        // TODO add your handling code here:
        btnAceptar.setBackground(Color.red);
    }//GEN-LAST:event_btnAceptarMouseEntered

    private void btnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseExited
        // TODO add your handling code here:
        btnAceptar.setBackground(new Color(0,136,204));
    }//GEN-LAST:event_btnAceptarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JTabbedPane categoria;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel pnCategoria;
    private javax.swing.JPanel pnProducto;
    private javax.swing.JTextField txtCanProducto;
    private javax.swing.JTextField txtNomProducto;
    private javax.swing.JTextField txtPrecioProducto;
    // End of variables declaration//GEN-END:variables
}
