/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import controladores.EmpleadosJpaController;
import empleados.ClaseEmpleados;
import entidades.Empleados;
import singleton.singleton;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author igeni
 */
public class FormEmpleados extends javax.swing.JPanel {

    //Clases.Conexion conexion = new Clases.Conexion();
    //Clases.InsertarEmpleado Insercion = new Clases.InsertarEmpleado();
    //Clases.Contrasena encriptado = new Clases.Contrasena();
    //Clases.Telefono telefono = new Clases.Telefono();
    ClaseEmpleados clasEmpleados = new ClaseEmpleados();
    //EmpleadosJpaController a = new EmpleadosJpaController(singleton.getConnection());
    DefaultTableModel empleados = new DefaultTableModel();
    DefaultTableModel clientes = new DefaultTableModel();
    int seleccionado = -1;
    int seltel = -1;
    int idseleccionado = -1;
    int conttel = -1;
    int contemp = -1;
    int clickemp = 0;
    int clicktel = 0;
    boolean EmpleadosAccionada = false;
    boolean TelefonosAccionada = false;
    public FormEmpleados() {
        initComponents();
        BTNEliEmpleado.setEnabled(false);
        //conexion.ConectarBaseDatos();
        TFNombres.setEnabled(true);
        TFDireccion.setEnabled(true);
        TFApellidos.setEnabled(true);
        TFMNombre.setEnabled(false);
        TFMApellidos.setEnabled(false);
        TFMDireccion.setEnabled(false);
        BTNAgregar.setEnabled(true);
        TFUsuario.setEnabled(true);
        PFContrasena.setEnabled(true);
        BTNModEmpleado.setEnabled(false);
        BTNEliEmpleado.setEnabled(false);
        RBVendedor.setEnabled(true);
        RBAdministrador.setEnabled(true);
        empleados.addColumn("Código");
        empleados.addColumn("Nombres");
        empleados.addColumn("Apellidos");
        empleados.addColumn("Dirección");
        empleados.addColumn("Teléfono");
        empleados.addColumn("Estado");
        empleados.addColumn("Usuario");
        empleados.addColumn("Rol");
        empleados.addColumn("Salario");
        TEmpleados.setModel(empleados);
        //Insercion.Buscar(empleados);
        //Insercion.Buscar(jComboBox1);
        //CrearModelo();
        cargarInformacion("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jPanel2 = new javax.swing.JPanel();
        PEmpleados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TEmpleados = new javax.swing.JTable();
        LBLMApellidos = new javax.swing.JLabel();
        LBLMDireccion = new javax.swing.JLabel();
        BTNModEmpleado = new javax.swing.JButton();
        LBLMNombre = new javax.swing.JLabel();
        PIngresoEmpleado = new javax.swing.JPanel();
        LBLApellidos = new javax.swing.JLabel();
        LBLDireccion = new javax.swing.JLabel();
        LBLNombre = new javax.swing.JLabel();
        RBVendedor = new javax.swing.JRadioButton();
        RBAdministrador = new javax.swing.JRadioButton();
        TFNombres = new javax.swing.JTextField();
        TFDireccion = new javax.swing.JTextField();
        PAdministrador = new javax.swing.JPanel();
        LBLUsuario = new javax.swing.JLabel();
        TFUsuario = new javax.swing.JTextField();
        LBLContrasena = new javax.swing.JLabel();
        PFContrasena = new javax.swing.JPasswordField();
        LBLUsuario2 = new javax.swing.JLabel();
        TFRespuesta = new javax.swing.JTextField();
        LBLUsuario3 = new javax.swing.JLabel();
        TFSalario = new javax.swing.JTextField();
        LBLUsuario1 = new javax.swing.JLabel();
        RBMascota = new javax.swing.JRadioButton();
        RBDeporte = new javax.swing.JRadioButton();
        RBMejorAmigo = new javax.swing.JRadioButton();
        BTNAgregar = new javax.swing.JButton();
        TFTelefono = new javax.swing.JTextField();
        LBLUsuario4 = new javax.swing.JLabel();
        TFApellidos = new javax.swing.JTextField();
        LBLBusqEmpleado = new javax.swing.JLabel();
        TFMNombre = new javax.swing.JTextField();
        TFMApellidos = new javax.swing.JTextField();
        TFMDireccion = new javax.swing.JTextField();
        TFFiltro = new javax.swing.JTextField();
        BTNEliEmpleado = new javax.swing.JButton();
        TFMSalario = new javax.swing.JTextField();
        LBLSalario = new javax.swing.JLabel();
        LBLMDireccion1 = new javax.swing.JLabel();
        TFMTelefono = new javax.swing.JTextField();
        LBLPanel = new javax.swing.JLabel();

        panel1.setBackground(new java.awt.Color(36, 41, 46));

        jPanel2.setBackground(new java.awt.Color(36, 41, 46));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        PEmpleados.setBackground(new java.awt.Color(36, 41, 46));

        TEmpleados = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        TEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Dirección", "Usuario"
            }
        ));
        TEmpleados.setFocusable(false);
        TEmpleados.getTableHeader().setReorderingAllowed(false);
        TEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TEmpleadosMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TEmpleadosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TEmpleados);

        LBLMApellidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLMApellidos.setForeground(new java.awt.Color(255, 255, 255));
        LBLMApellidos.setText("Apellidos:");

        LBLMDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLMDireccion.setForeground(new java.awt.Color(255, 255, 255));
        LBLMDireccion.setText("Dirección:");

        BTNModEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Modificarp.png"))); // NOI18N
        BTNModEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModEmpleadoActionPerformed(evt);
            }
        });

        LBLMNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLMNombre.setForeground(new java.awt.Color(255, 255, 255));
        LBLMNombre.setText("Nombres:");

        PIngresoEmpleado.setBackground(new java.awt.Color(36, 41, 46));

        LBLApellidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLApellidos.setForeground(new java.awt.Color(255, 255, 255));
        LBLApellidos.setText("Apellidos:");

        LBLDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLDireccion.setForeground(new java.awt.Color(255, 255, 255));
        LBLDireccion.setText("Dirección:");

        LBLNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLNombre.setForeground(new java.awt.Color(255, 255, 255));
        LBLNombre.setText("Nombres:");

        RBVendedor.setBackground(new java.awt.Color(36, 41, 46));
        RBVendedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RBVendedor.setForeground(new java.awt.Color(255, 255, 255));
        RBVendedor.setText("Vendedor");
        RBVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBVendedorActionPerformed(evt);
            }
        });

        RBAdministrador.setBackground(new java.awt.Color(36, 41, 46));
        RBAdministrador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RBAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        RBAdministrador.setText("Administrador");
        RBAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBAdministradorActionPerformed(evt);
            }
        });

        TFNombres.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFNombresKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFNombresKeyTyped(evt);
            }
        });

        TFDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFDireccionActionPerformed(evt);
            }
        });
        TFDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFDireccionKeyTyped(evt);
            }
        });

        PAdministrador.setBackground(new java.awt.Color(36, 41, 46));

        javax.swing.GroupLayout PAdministradorLayout = new javax.swing.GroupLayout(PAdministrador);
        PAdministrador.setLayout(PAdministradorLayout);
        PAdministradorLayout.setHorizontalGroup(
            PAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
        PAdministradorLayout.setVerticalGroup(
            PAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        LBLUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LBLUsuario.setText("Usuario:");

        TFUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFUsuarioKeyTyped(evt);
            }
        });

        LBLContrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLContrasena.setForeground(new java.awt.Color(255, 255, 255));
        LBLContrasena.setText("Contraseña:");

        PFContrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PFContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PFContrasenaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PFContrasenaKeyTyped(evt);
            }
        });

        LBLUsuario2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLUsuario2.setForeground(new java.awt.Color(255, 255, 255));
        LBLUsuario2.setText("Respuesta:");

        TFRespuesta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFRespuesta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFRespuestaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFRespuestaKeyTyped(evt);
            }
        });

        LBLUsuario3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLUsuario3.setForeground(new java.awt.Color(255, 255, 255));
        LBLUsuario3.setText("Salario:");

        TFSalario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFSalarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFSalarioKeyTyped(evt);
            }
        });

        LBLUsuario1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        LBLUsuario1.setText("Preguntas de respaldo:");

        RBMascota.setBackground(new java.awt.Color(36, 41, 46));
        RBMascota.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RBMascota.setForeground(new java.awt.Color(255, 255, 255));
        RBMascota.setText("Mi mascota preferida sería:");
        RBMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMascotaActionPerformed(evt);
            }
        });

        RBDeporte.setBackground(new java.awt.Color(36, 41, 46));
        RBDeporte.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RBDeporte.setForeground(new java.awt.Color(255, 255, 255));
        RBDeporte.setText("Mi deporte favorito es:");
        RBDeporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBDeporteActionPerformed(evt);
            }
        });

        RBMejorAmigo.setBackground(new java.awt.Color(36, 41, 46));
        RBMejorAmigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RBMejorAmigo.setForeground(new java.awt.Color(255, 255, 255));
        RBMejorAmigo.setText("Mi papá se llama:");
        RBMejorAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMejorAmigoActionPerformed(evt);
            }
        });

        BTNAgregar.setForeground(new java.awt.Color(240, 240, 240));
        BTNAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregarp.png"))); // NOI18N
        BTNAgregar.setBorder(null);
        BTNAgregar.setBorderPainted(false);
        BTNAgregar.setContentAreaFilled(false);
        BTNAgregar.setFocusPainted(false);
        BTNAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNAgregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agrega_empleado2.png"))); // NOI18N
        BTNAgregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agrega_empleado1.png"))); // NOI18N
        BTNAgregar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTNAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAgregarActionPerformed(evt);
            }
        });

        TFTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFTelefonoKeyTyped(evt);
            }
        });

        LBLUsuario4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLUsuario4.setForeground(new java.awt.Color(255, 255, 255));
        LBLUsuario4.setText("Telefono:");

        TFApellidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFApellidosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFApellidosKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PIngresoEmpleadoLayout = new javax.swing.GroupLayout(PIngresoEmpleado);
        PIngresoEmpleado.setLayout(PIngresoEmpleadoLayout);
        PIngresoEmpleadoLayout.setHorizontalGroup(
            PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                        .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RBAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TFTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .addComponent(TFSalario, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                        .addComponent(TFNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                        .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                                .addComponent(RBVendedor)
                                .addGap(29, 29, 29))
                            .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                                .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LBLNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LBLApellidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LBLDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)))
                        .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBLContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LBLUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(LBLUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(LBLUsuario))))
                    .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                        .addComponent(TFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PFContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(BTNAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(LBLUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBDeporte)
                            .addComponent(RBMascota)
                            .addComponent(RBMejorAmigo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PIngresoEmpleadoLayout.setVerticalGroup(
            PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                .addComponent(PAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                        .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(LBLUsuario)
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PIngresoEmpleadoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LBLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLContrasena)
                            .addComponent(LBLApellidos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PFContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLDireccion)
                            .addComponent(LBLUsuario2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBVendedor)
                            .addComponent(LBLUsuario3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PIngresoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBAdministrador)
                            .addComponent(TFSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PIngresoEmpleadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBLUsuario1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RBMascota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RBDeporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RBMejorAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(LBLUsuario4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LBLBusqEmpleado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLBusqEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        LBLBusqEmpleado.setText("Buscar por nombre:");

        TFMNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFMNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFMNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFMNombreKeyTyped(evt);
            }
        });

        TFMApellidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFMApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFMApellidosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFMApellidosKeyTyped(evt);
            }
        });

        TFMDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFMDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFMDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFMDireccionKeyTyped(evt);
            }
        });

        TFFiltro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFFiltroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFFiltroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFFiltroKeyTyped(evt);
            }
        });

        BTNEliEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminarp.png"))); // NOI18N
        BTNEliEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliEmpleadoActionPerformed(evt);
            }
        });

        TFMSalario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFMSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFMSalarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFMSalarioKeyTyped(evt);
            }
        });

        LBLSalario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLSalario.setForeground(new java.awt.Color(255, 255, 255));
        LBLSalario.setText("Salario:");

        LBLMDireccion1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLMDireccion1.setForeground(new java.awt.Color(255, 255, 255));
        LBLMDireccion1.setText("Teléfono:");

        TFMTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFMTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFMTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFMTelefonoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PEmpleadosLayout = new javax.swing.GroupLayout(PEmpleados);
        PEmpleados.setLayout(PEmpleadosLayout);
        PEmpleadosLayout.setHorizontalGroup(
            PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PEmpleadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLBusqEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PEmpleadosLayout.createSequentialGroup()
                                .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PEmpleadosLayout.createSequentialGroup()
                                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TFMNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LBLMNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LBLSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LBLMApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TFMApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LBLMDireccion)))
                                    .addGroup(PEmpleadosLayout.createSequentialGroup()
                                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LBLMDireccion1)
                                            .addComponent(TFMTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addComponent(BTNModEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(119, 119, 119)
                                .addComponent(PIngresoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TFFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(344, 344, 344))
                    .addGroup(PEmpleadosLayout.createSequentialGroup()
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PEmpleadosLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(BTNEliEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PEmpleadosLayout.createSequentialGroup()
                                .addComponent(TFMSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TFMDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PEmpleadosLayout.setVerticalGroup(
            PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PEmpleadosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(LBLBusqEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNEliEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PEmpleadosLayout.createSequentialGroup()
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLMNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLMApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFMNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFMApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBLSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLMDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFMSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFMDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PEmpleadosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LBLMDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TFMTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PEmpleadosLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(BTNModEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(PEmpleadosLayout.createSequentialGroup()
                        .addComponent(PIngresoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 301, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        LBLPanel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBLPanel.setForeground(new java.awt.Color(255, 255, 255));
        LBLPanel.setText("Ingreso de empleados");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(PEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3215, 3215, 3215)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(LBLPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LBLPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CrearModelo(){
        try {
            empleados = (new DefaultTableModel(null, new String [] {
            "Código", "Nombres","Apellidos", "Direccion", "Telefono",
            "Estado","Usuario","Rol", "Salario"}){
            Class[] types = new Class [] {
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
            false,false,false,false, false
            };
            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex){
                return canEdit [colIndex];
            }
            });
            TEmpleados.setModel(empleados);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.toString()+"error2");
        }
    }
    private void cargarInformacion(String contenido)
    {
        try{
            Object O[] = null;
            List<entidades.Empleados> lista = clasEmpleados.buscarObjects(contenido);
            
            for(int i = 0; i < lista.size(); i++)
            {
                    empleados.addRow(O);
                    empleados.setValueAt(lista.get(i).getId(), i, 0);
                    empleados.setValueAt(lista.get(i).getNombre(), i, 1);
                    empleados.setValueAt(lista.get(i).getApellido(), i, 2);
                    empleados.setValueAt(lista.get(i).getDireccion(), i, 3);
                    empleados.setValueAt(lista.get(i).getTelefono(), i, 4);
                    empleados.setValueAt(lista.get(i).getEstado(), i, 5);
                    empleados.setValueAt(lista.get(i).getUsuario(), i, 6);
                    empleados.setValueAt(lista.get(i).getAdministrador(), i, 7);
                    empleados.setValueAt(lista.get(i).getSalario(), i, 8);
            }
            TEmpleados.setModel(empleados);
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    private void BTNEliEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEliEmpleadoActionPerformed
        EliminarEmpleado();
    }//GEN-LAST:event_BTNEliEmpleadoActionPerformed
    
    private void EliminarEmpleado()
    {
        EmpleadosJpaController ejc = new EmpleadosJpaController(singleton.getConnection());
        Empleados empleado = ejc.findEmpleados(idseleccionado);
        while(empleados.getRowCount()>0)
            empleados.removeRow(0);
        while(clientes.getRowCount()>0)
            clientes.removeRow(0);
        System.out.println(TEmpleados.getSelectedRow());
        if (idseleccionado != -1)
        {
            if (!empleado.getEstado().equals("Inactivo"))
            {
                empleado.setEstado("Inactivo");
                clasEmpleados.eliminarObject(empleado, singleton.getConnection(), idseleccionado);
                
                TFDireccion.setText("");
                TFApellidos.setText("");
                TFNombres.setText("");
                TFMNombre.setText("");
                TFMApellidos.setText("");
                TFMDireccion.setText("");
                TFUsuario.setText("");
                PFContrasena.setText("");
                TFFiltro.setText("");
                BTNEliEmpleado.setEnabled(false);
                BTNModEmpleado.setEnabled(false);
                TFMNombre.setEnabled(false);
                TFMApellidos.setEnabled(false);
                TFMDireccion.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Empleado despedido con éxito");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Por favor seleccione un empleado");
        cargarInformacion("");
    }
    private void TEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TEmpleadosMouseClicked

    }//GEN-LAST:event_TEmpleadosMouseClicked

    private void SeleccionarEmpleado()
    {
        EmpleadosAccionada = true;
        TelefonosAccionada = false;
        while(clientes.getRowCount()>0)
            clientes.removeRow(0);
        int indice = TEmpleados.getSelectedRow() + 1;
        seleccionado = indice;
        idseleccionado = Integer.parseInt(String.valueOf(TEmpleados.getValueAt(TEmpleados.getSelectedRow(), 0)));
        TableModel modelo = TEmpleados.getModel();
        if (indice > 0)
        {
            BTNEliEmpleado.setEnabled(true);
            BTNModEmpleado.setEnabled(true);
            TFMNombre.setEnabled(true);
            TFMApellidos.setEnabled(true);
            TFMDireccion.setEnabled(true);
            TFUsuario.setEnabled(true);
            PFContrasena.setEnabled(true);
        }
    }
    private void BTNModEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModEmpleadoActionPerformed
        ModificarEmpleado();
    }//GEN-LAST:event_BTNModEmpleadoActionPerformed

    private void ModificarEmpleado()
    {
        EmpleadosJpaController ejc = new EmpleadosJpaController(singleton.getConnection());
        Empleados empleado = ejc.findEmpleados(idseleccionado);
        while(empleados.getRowCount()>0)
        empleados.removeRow(0);
        while(clientes.getRowCount()>0)
        clientes.removeRow(0);
        if (TFMDireccion.getText().equals("") || TFMNombre.getText().equals("") || TFMApellidos.getText().equals("") || TFMSalario.getText().equals("") || TFMTelefono.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Por favor rellene al menos una de las tres casillas para modificar.");
            while(empleados.getRowCount()>0)
                empleados.removeRow(0);
            while(clientes.getRowCount()>0)
                clientes.removeRow(0);
        }
        else
        {
            empleado.setId(idseleccionado);
            empleado.setNombre(TFMNombre.getText());
            empleado.setApellido(TFMApellidos.getText());
            empleado.setDireccion(TFMDireccion.getText());
            empleado.setSalario(Float.valueOf(TFMSalario.getText()));
            empleado.setTelefono(TFMTelefono.getText());
            clasEmpleados.editarObject(empleado, singleton.getConnection(), idseleccionado);
            JOptionPane.showMessageDialog(null, "Modificación exitosa");
            TFDireccion.setText("");
            TFApellidos.setText("");
            TFNombres.setText("");
            TFMNombre.setText("");
            TFMApellidos.setText("");
            TFMDireccion.setText("");
            TFMSalario.setText("");
            TFMTelefono.setText("");
            TFUsuario.setText("");
            PFContrasena.setText("");
            TFFiltro.setText("");
            BTNEliEmpleado.setEnabled(false);
            BTNModEmpleado.setEnabled(false);
            TFMNombre.setEnabled(false);
            TFMApellidos.setEnabled(false);
            TFMDireccion.setEnabled(false);
        }
        seleccionado = -1;
        idseleccionado = -1;
        cargarInformacion("");
    }
    private void BTNAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAgregarActionPerformed
        AgregarEmpleado();
    }//GEN-LAST:event_BTNAgregarActionPerformed

      /*  public List filtrar(String filtrado)
    {
        Query query = emf.createNamedQuery("Empleados.filtring", Empleados.class);
        query.setParameter("nombrefilter", filtrado+"%");
        return query.getResultList();
    }*/
    
    //@NamedQuery(name = "Empleados.filtring", query = "SELECT e FROM Empleados e WHERE e.nombre LIKE :nombrefilter" )
    
    private void AgregarEmpleado()
    {
        
        Empleados empleado = new Empleados();
        while(empleados.getRowCount()>0)
            empleados.removeRow(0);
        while(clientes.getRowCount()>0)
            clientes.removeRow(0);
        seleccionado = -1;
        if (TFDireccion.getText().length() > 0 && TFApellidos.getText().length() > 0 && TFNombres.getText().length() > 0
                && TFUsuario.getText().length() > 0 && PFContrasena.getPassword().length > 0 && TFRespuesta.getText().length() > 0 && TFSalario.getText().length() > 0 &&
                TFTelefono.getText().length() > 0 && 
                (RBVendedor.isSelected() || RBAdministrador.isSelected()) && (RBMascota.isSelected() || RBDeporte.isSelected()
                || RBMejorAmigo.isSelected()))        
        {
                     if (RBVendedor.isSelected())
                        if(RBMascota.isSelected())
                        {
                            empleado.setNombre(TFNombres.getText());
                            empleado.setApellido(TFApellidos.getText());
                            empleado.setDireccion(TFDireccion.getText());
                            empleado.setUsuario(TFUsuario.getText());
                            empleado.setContrasena(String.valueOf(PFContrasena.getPassword()));
                            empleado.setAdministrador((short)0);
                            empleado.setPregunta(RBMascota.getText());
                            empleado.setRespuesta(TFRespuesta.getText());
                            empleado.setEstado("Activo");
                            empleado.setSalario(Float.valueOf(TFSalario.getText()));
                            empleado.setTelefono(TFTelefono.getText());
                            clasEmpleados.registrarObject(empleado, singleton.getConnection());
                        }
                        else if (RBDeporte.isSelected())
                        {
                            empleado.setNombre(TFNombres.getText());
                            empleado.setApellido(TFApellidos.getText());
                            empleado.setDireccion(TFDireccion.getText());
                            empleado.setUsuario(TFUsuario.getText());
                            empleado.setContrasena(String.valueOf(PFContrasena.getPassword()));
                            empleado.setAdministrador((short)0);
                            empleado.setPregunta(RBDeporte.getText());
                            empleado.setRespuesta(TFRespuesta.getText());
                            empleado.setEstado("Activo");
                            empleado.setSalario(Float.valueOf(TFSalario.getText()));
                            empleado.setTelefono(TFTelefono.getText());
                            clasEmpleados.registrarObject(empleado, singleton.getConnection());
                        }
                        else if (RBMejorAmigo.isSelected())
                        {
                            empleado.setNombre(TFNombres.getText());
                            empleado.setApellido(TFApellidos.getText());
                            empleado.setDireccion(TFDireccion.getText());
                            empleado.setUsuario(TFUsuario.getText());
                            empleado.setContrasena(String.valueOf(PFContrasena.getPassword()));
                            empleado.setAdministrador((short)0);
                            empleado.setPregunta(RBMejorAmigo.getText());
                            empleado.setRespuesta(TFRespuesta.getText());
                            empleado.setEstado("Activo");
                            empleado.setSalario(Float.valueOf(TFSalario.getText()));
                            empleado.setTelefono(TFTelefono.getText());
                            clasEmpleados.registrarObject(empleado, singleton.getConnection());
                        }
                    else if (RBAdministrador.isSelected())
                        if(RBMascota.isSelected())
                        {
                            empleado.setNombre(TFNombres.getText());
                            empleado.setApellido(TFApellidos.getText());
                            empleado.setDireccion(TFDireccion.getText());
                            empleado.setUsuario(TFUsuario.getText());
                            empleado.setContrasena(String.valueOf(PFContrasena.getPassword()));
                            empleado.setAdministrador((short)1);
                            empleado.setPregunta(RBMascota.getText());
                            empleado.setRespuesta(TFRespuesta.getText());
                            empleado.setEstado("Activo");
                            empleado.setSalario(Float.valueOf(TFSalario.getText()));
                            empleado.setTelefono(TFTelefono.getText());
                            clasEmpleados.registrarObject(empleado, singleton.getConnection());
                        }
                        else if (RBDeporte.isSelected())
                        {
                            empleado.setNombre(TFNombres.getText());
                            empleado.setApellido(TFApellidos.getText());
                            empleado.setDireccion(TFDireccion.getText());
                            empleado.setUsuario(TFUsuario.getText());
                            empleado.setContrasena(String.valueOf(PFContrasena.getPassword()));
                            empleado.setAdministrador((short)1);
                            empleado.setPregunta(RBDeporte.getText());
                            empleado.setRespuesta(TFRespuesta.getText());
                            empleado.setEstado("Activo");
                            empleado.setSalario(Float.valueOf(TFSalario.getText()));
                            empleado.setTelefono(TFTelefono.getText());
                            clasEmpleados.registrarObject(empleado, singleton.getConnection());
                        }
                        else if (RBMejorAmigo.isSelected())
                        {
                            empleado.setNombre(TFNombres.getText());
                            empleado.setApellido(TFApellidos.getText());
                            empleado.setDireccion(TFDireccion.getText());
                            empleado.setUsuario(TFUsuario.getText());
                            empleado.setContrasena(String.valueOf(PFContrasena.getPassword()));
                            empleado.setAdministrador((short)1);
                            empleado.setPregunta(RBMejorAmigo.getText());
                            empleado.setRespuesta(TFRespuesta.getText());
                            empleado.setEstado("Activo");
                            empleado.setSalario(Float.valueOf(TFSalario.getText()));
                            empleado.setTelefono(TFTelefono.getText());
                            clasEmpleados.registrarObject(empleado, singleton.getConnection());
                        }
                TFDireccion.setText("");
                TFApellidos.setText("");
                TFNombres.setText("");
                TFMNombre.setText("");
                TFMApellidos.setText("");
                TFMDireccion.setText("");
                TFUsuario.setText("");
                TFTelefono.setText("");
                PFContrasena.setText("");
                TFFiltro.setText("");
                TFSalario.setText("");
                BTNEliEmpleado.setEnabled(false);                
                BTNModEmpleado.setEnabled(false);
                TFMNombre.setEnabled(false);
                TFMApellidos.setEnabled(false);
                TFMDireccion.setEnabled(false);
                RBVendedor.setSelected(false);
                RBAdministrador.setSelected(false);
                RBMascota.setSelected(false);
                RBDeporte.setSelected(false);
                RBMejorAmigo.setSelected(false);
                TFRespuesta.setText("");
            
        }
        else
            JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos");
        while(empleados.getRowCount()>0)
        empleados.removeRow(0);
        while(clientes.getRowCount()>0)
        clientes.removeRow(0);
        cargarInformacion("");
    }
    private void RBVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBVendedorActionPerformed
        if (RBVendedor.isSelected())
            RBAdministrador.setSelected(false);
    }//GEN-LAST:event_RBVendedorActionPerformed

    private void RBAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBAdministradorActionPerformed
        if (RBAdministrador.isSelected())
            RBVendedor.setSelected(false);
    }//GEN-LAST:event_RBAdministradorActionPerformed

    private void TFFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltroKeyTyped
        if (TFFiltro.getText().length() > 30) evt.consume();
        
    }//GEN-LAST:event_TFFiltroKeyTyped

    private void TFMNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMNombreKeyTyped
        char c = evt.getKeyChar();
        
        if ((c<'a' || c>'z') && (c<'A')|c>'Z')
        {
            if (c != ' ')
                evt.consume();
        }
        if (TFMNombre.getText().length() > 30) evt.consume();
    }//GEN-LAST:event_TFMNombreKeyTyped

    private void TFMApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMApellidosKeyTyped
        char c = evt.getKeyChar();
        
        if ((c<'a' || c>'z') && (c<'A')|c>'Z')
        {
            if (c != ' ')
                evt.consume();
        }
        if (TFMApellidos.getText().length() > 30) evt.consume();
    }//GEN-LAST:event_TFMApellidosKeyTyped

    private void TFMDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMDireccionKeyTyped
        char c = evt.getKeyChar();
        if ((c<'a' || c>'z') && (c<'A')|c>'Z') 
        {
            if (c < '0' || c > '9')
            {
                if (c != '-')
                {
                    if (c != ' ')
                        evt.consume();
                }
            }
        }
        if (TFMDireccion.getText().length() > 45) evt.consume();
    }//GEN-LAST:event_TFMDireccionKeyTyped

    private void TFNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNombresKeyTyped
        char c = evt.getKeyChar();
        
        if ((c<'a' || c>'z') && (c<'A')|c>'Z')
        {
            if (c != ' ')
                evt.consume();
        }
        if (TFNombres.getText().length() > 30) evt.consume();
        
    }//GEN-LAST:event_TFNombresKeyTyped

    private void TFApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFApellidosKeyTyped
        char c = evt.getKeyChar();
        
        if ((c<'a' || c>'z') && (c<'A')|c>'Z')
        {
            if (c != ' ')
                evt.consume();
        }
        if (TFApellidos.getText().length() > 30) evt.consume();
        
    }//GEN-LAST:event_TFApellidosKeyTyped

    private void TFDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFDireccionKeyTyped
        char c = evt.getKeyChar();
        if ((c<'a' || c>'z') && (c<'A')|c>'Z') 
        {
            if (c < '0' || c > '9')
            {
                if (c != '-')
                {
                    if (c != ' ')
                        evt.consume();
                }
            }
        }
        if (TFApellidos.getText().length() > 45) evt.consume();
        
    }//GEN-LAST:event_TFDireccionKeyTyped

    private void TFUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFUsuarioKeyTyped
        char c = evt.getKeyChar();
        if ((c<'a' || c>'z') && (c<'A')|c>'Z') 
        {
            if (c < '0' || c > '9')
            {
                    evt.consume();
            }
        }
        if (TFUsuario.getText().length() > 25) evt.consume();
        
    }//GEN-LAST:event_TFUsuarioKeyTyped

    private void PFContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PFContrasenaKeyTyped
        char c = evt.getKeyChar();
        if (PFContrasena.getPassword().length > 40) evt.consume();
        
    }//GEN-LAST:event_PFContrasenaKeyTyped

    private void TFFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltroKeyPressed
        
    }//GEN-LAST:event_TFFiltroKeyPressed

    private void TFFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFFiltroKeyReleased
        while(empleados.getRowCount()>0)
            empleados.removeRow(0);
        while(clientes.getRowCount()>0)
            clientes.removeRow(0);
        cargarInformacion(TFFiltro.getText());
    }//GEN-LAST:event_TFFiltroKeyReleased

    private void RBMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMascotaActionPerformed
        if (RBMascota.isSelected())
        {
            RBDeporte.setSelected(false);
            RBMejorAmigo.setSelected(false);
        }
    }//GEN-LAST:event_RBMascotaActionPerformed

    private void RBDeporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBDeporteActionPerformed
        if (RBDeporte.isSelected())
        {
            RBMascota.setSelected(false);
            RBMejorAmigo.setSelected(false);
        }
    }//GEN-LAST:event_RBDeporteActionPerformed

    private void RBMejorAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMejorAmigoActionPerformed
        if (RBMejorAmigo.isSelected())
        {
            RBMascota.setSelected(false);
            RBDeporte.setSelected(false);
        }
    }//GEN-LAST:event_RBMejorAmigoActionPerformed

    private void TFRespuestaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFRespuestaKeyTyped
        char c = evt.getKeyChar();
        if (TFRespuesta.getText().length() > 30) evt.consume();
    }//GEN-LAST:event_TFRespuestaKeyTyped

    private void TFDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFDireccionActionPerformed

    private void TFNombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNombresKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            TFApellidos.requestFocus();
    }//GEN-LAST:event_TFNombresKeyPressed

    private void TFApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFApellidosKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) TFDireccion.requestFocus();
    }//GEN-LAST:event_TFApellidosKeyPressed

    private void TFDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFDireccionKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) TFUsuario.requestFocus();
    }//GEN-LAST:event_TFDireccionKeyPressed

    private void TFUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFUsuarioKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) PFContrasena.requestFocus();
    }//GEN-LAST:event_TFUsuarioKeyPressed

    private void PFContrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PFContrasenaKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) TFRespuesta.requestFocus();
    }//GEN-LAST:event_PFContrasenaKeyPressed

    private void TFRespuestaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFRespuestaKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) AgregarEmpleado();
    }//GEN-LAST:event_TFRespuestaKeyPressed

    private void TFMNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMNombreKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) TFMApellidos.requestFocus();
    }//GEN-LAST:event_TFMNombreKeyPressed

    private void TFMApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMApellidosKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) TFMDireccion.requestFocus();
    }//GEN-LAST:event_TFMApellidosKeyPressed

    private void TFMDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMDireccionKeyPressed
        
    }//GEN-LAST:event_TFMDireccionKeyPressed

    private void TEmpleadosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TEmpleadosMouseReleased
        contemp = idseleccionado;
        SeleccionarEmpleado();
        if (contemp == idseleccionado)
            clickemp ++;
        else
            clickemp = 0;
        if (clickemp == 3)
        {
            EliminarEmpleado();
            clickemp = 0;
        }
    }//GEN-LAST:event_TEmpleadosMouseReleased

    private void TFSalarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFSalarioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSalarioKeyPressed

    private void TFSalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFSalarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSalarioKeyTyped

    private void TFMSalarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMSalarioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFMSalarioKeyPressed

    private void TFMSalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMSalarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TFMSalarioKeyTyped

    private void TFTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTelefonoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTelefonoKeyPressed

    private void TFTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTelefonoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTelefonoKeyTyped

    private void TFMTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMTelefonoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFMTelefonoKeyPressed

    private void TFMTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFMTelefonoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TFMTelefonoKeyTyped

    
        private void ValidarNombreYApellido(JTextField textfield, boolean direccion)
    {
        textfield.addKeyListener(new KeyAdapter()
{
   public void keyTyped(KeyEvent e)
   {
      char caracter = e.getKeyChar();

      // Verificar si la tecla pulsada no es un digito
      if(((caracter < '0') ||
         (caracter > '9')) &&
         (caracter != '\b' /*corresponde a BACK_SPACE*/))
      {
         e.consume();  // ignorar el evento de teclado
      }
   }
});
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAgregar;
    private javax.swing.JButton BTNEliEmpleado;
    private javax.swing.JButton BTNModEmpleado;
    private javax.swing.JLabel LBLApellidos;
    private javax.swing.JLabel LBLBusqEmpleado;
    private javax.swing.JLabel LBLContrasena;
    private javax.swing.JLabel LBLDireccion;
    private javax.swing.JLabel LBLMApellidos;
    private javax.swing.JLabel LBLMDireccion;
    private javax.swing.JLabel LBLMDireccion1;
    private javax.swing.JLabel LBLMNombre;
    private javax.swing.JLabel LBLNombre;
    private javax.swing.JLabel LBLPanel;
    private javax.swing.JLabel LBLSalario;
    private javax.swing.JLabel LBLUsuario;
    private javax.swing.JLabel LBLUsuario1;
    private javax.swing.JLabel LBLUsuario2;
    private javax.swing.JLabel LBLUsuario3;
    private javax.swing.JLabel LBLUsuario4;
    private javax.swing.JPanel PAdministrador;
    private javax.swing.JPanel PEmpleados;
    private javax.swing.JPasswordField PFContrasena;
    private javax.swing.JPanel PIngresoEmpleado;
    private javax.swing.JRadioButton RBAdministrador;
    private javax.swing.JRadioButton RBDeporte;
    private javax.swing.JRadioButton RBMascota;
    private javax.swing.JRadioButton RBMejorAmigo;
    private javax.swing.JRadioButton RBVendedor;
    private javax.swing.JTable TEmpleados;
    private javax.swing.JTextField TFApellidos;
    private javax.swing.JTextField TFDireccion;
    private javax.swing.JTextField TFFiltro;
    private javax.swing.JTextField TFMApellidos;
    private javax.swing.JTextField TFMDireccion;
    private javax.swing.JTextField TFMNombre;
    private javax.swing.JTextField TFMSalario;
    private javax.swing.JTextField TFMTelefono;
    private javax.swing.JTextField TFNombres;
    private javax.swing.JTextField TFRespuesta;
    private javax.swing.JTextField TFSalario;
    private javax.swing.JTextField TFTelefono;
    private javax.swing.JTextField TFUsuario;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
