/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import controladores.EmpleadosJpaController;
import controladores.TelefonosJpaController;
import recursoshumanos.ClaseEmpleados;
import entidades.Empleados;
import entidades.Telefonos;
import java.awt.BorderLayout;
import java.awt.Image;
import singleton.singleton;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.MaskFormatter;
import recursoshumanos.ClaseTelefonos;

/**
 *
 * @author igeni
 */
public class FormEmpleados extends javax.swing.JPanel {
    ClaseEmpleados clasEmpleados = new ClaseEmpleados();
    DefaultTableModel empleados = new DefaultTableModel();
    DefaultTableModel clientes = new DefaultTableModel();
    ClaseTelefonos clasTelefonos = new ClaseTelefonos();
    int seleccionado = -1;
    int seltel = -1;
    int idseleccionado = -1;
    int conttel = -1;
    int contemp = -1;
    int clickemp = 0;
    int clicktel = 0;
    Empleados empleado;
    boolean mostrartodosEmp = false;
    DecimalFormat num = new DecimalFormat("#,###.00");
    public FormEmpleados() {
        initComponents();
        btnEliEmpleado.setEnabled(false);        
        limpiarTodo();
        rbActividad.setSelected(true);
        rbTodos.setSelected(false);
        empleados.addColumn("Código");
        empleados.addColumn("Nombres");
        empleados.addColumn("Apellidos");
        empleados.addColumn("Dirección");
        empleados.addColumn("Estado");
        empleados.addColumn("Rol");
        empleados.addColumn("Salario");
        clientes.addColumn("Teléfono");
        tEmpleados.setModel(empleados);
        tTelefonos.setModel(clientes);
        cargarInformacion("");
    }
    
    private void limpiarTodo()
    {
        lblBusqTel.setText("Buscar teléfono de:");
        lblMTelefono.setText("Teléfono/Celular de:");
        lblAgregarTelefono.setText("Agregar teléfono a:");
        tfMNombre.setEnabled(false);
        tfMApellidos.setEnabled(false);
        tfMDireccion.setEnabled(false);
        tfMSalario.setEnabled(false);
        tfMTelefono.setEnabled(false);
        tfTelefono.setEnabled(false);
        tfFiltro1.setEnabled(false);
        lblPagar.setEnabled(false);
        lblPagar.setVisible(false);
        tfMNombre.setText("");
        tfMApellidos.setText("");
        tfMDireccion.setText("");
        tfMSalario.setText("");
        tfMTelefono.setText("");
        tfTelefono.setText("");
        tfFiltro1.setText("");
        btnModEmpleado.setEnabled(false);
        btnEliEmpleado.setEnabled(false);
        btnEliTel.setEnabled(false);
        btnModCel.setEnabled(false);
        btnTelefono.setEnabled(false);
        rbMRol.setEnabled(false);
        rbMRol.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jPanel2 = new javax.swing.JPanel();
        PEmpleados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tEmpleados = new javax.swing.JTable();
        lblBusqEmpleado = new javax.swing.JLabel();
        tfFiltro = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblMNombre = new javax.swing.JLabel();
        tfMNombre = new javax.swing.JTextField();
        lblMApellidos = new javax.swing.JLabel();
        tfMApellidos = new javax.swing.JTextField();
        lblMSalario = new javax.swing.JLabel();
        tfMSalario = new javax.swing.JTextField();
        lblMDireccion = new javax.swing.JLabel();
        tfMDireccion = new javax.swing.JTextField();
        btnModEmpleado = new javax.swing.JButton();
        PTelefono1 = new javax.swing.JPanel();
        btnEliTel = new javax.swing.JButton();
        PIngresoTelefono1 = new javax.swing.JPanel();
        lblAgregarTelefono = new javax.swing.JLabel();
        btnTelefono = new javax.swing.JButton();
        tfTelefono = new javax.swing.JTextField();
        btnModCel = new javax.swing.JButton();
        tfMTelefono = new javax.swing.JTextField();
        lblMTelefono = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tTelefonos = new javax.swing.JTable();
        tfFiltro1 = new javax.swing.JTextField();
        lblBusqTel = new javax.swing.JLabel();
        lblPagar = new javax.swing.JLabel();
        btnEliEmpleado = new javax.swing.JButton();
        rbMRol = new javax.swing.JRadioButton();
        btnAgregarEmpleado = new javax.swing.JButton();
        rbActividad = new javax.swing.JRadioButton();
        rbTodos = new javax.swing.JRadioButton();
        lblBusqLista = new javax.swing.JLabel();
        lblDatos = new javax.swing.JLabel();

        panel1.setBackground(new java.awt.Color(36, 41, 46));

        jPanel2.setBackground(new java.awt.Color(36, 41, 46));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        PEmpleados.setBackground(new java.awt.Color(36, 41, 46));

        tEmpleados = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Dirección", "Usuario"
            }
        ));
        tEmpleados.setFocusable(false);
        tEmpleados.getTableHeader().setReorderingAllowed(false);
        tEmpleados.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tEmpleadosMouseDragged(evt);
            }
        });
        tEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tEmpleadosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tEmpleadosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tEmpleadosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tEmpleados);

        lblBusqEmpleado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBusqEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        lblBusqEmpleado.setText("Buscar por nombre:");

        tfFiltro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfFiltroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFiltroKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFiltroKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(36, 41, 46));

        lblMNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblMNombre.setText("Nombres:");

        tfMNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfMNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMNombreActionPerformed(evt);
            }
        });
        tfMNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfMNombreKeyTyped(evt);
            }
        });

        lblMApellidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMApellidos.setForeground(new java.awt.Color(255, 255, 255));
        lblMApellidos.setText("Apellidos:");

        tfMApellidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfMApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMApellidosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfMApellidosKeyTyped(evt);
            }
        });

        lblMSalario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMSalario.setForeground(new java.awt.Color(255, 255, 255));
        lblMSalario.setText("Salario (Q.):");

        tfMSalario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfMSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMSalarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfMSalarioKeyTyped(evt);
            }
        });

        lblMDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblMDireccion.setText("Dirección:");

        tfMDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfMDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfMDireccionKeyTyped(evt);
            }
        });

        btnModEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Modificarp.png"))); // NOI18N
        btnModEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModEmpleadoActionPerformed(evt);
            }
        });

        PTelefono1.setBackground(new java.awt.Color(36, 41, 46));

        btnEliTel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminarp.png"))); // NOI18N
        btnEliTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliTelActionPerformed(evt);
            }
        });

        PIngresoTelefono1.setBackground(new java.awt.Color(36, 41, 46));

        lblAgregarTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAgregarTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarTelefono.setText("Teléfono/Celular del empleado:");

        btnTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar_telefono.png"))); // NOI18N
        btnTelefono.setBorder(null);
        btnTelefono.setBorderPainted(false);
        btnTelefono.setContentAreaFilled(false);
        btnTelefono.setFocusPainted(false);
        btnTelefono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTelefono.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar_telefono2.png"))); // NOI18N
        btnTelefono.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agregar_telefono1.png"))); // NOI18N
        btnTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelefonoActionPerformed(evt);
            }
        });

        tfTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTelefonoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PIngresoTelefono1Layout = new javax.swing.GroupLayout(PIngresoTelefono1);
        PIngresoTelefono1.setLayout(PIngresoTelefono1Layout);
        PIngresoTelefono1Layout.setHorizontalGroup(
            PIngresoTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PIngresoTelefono1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PIngresoTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgregarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PIngresoTelefono1Layout.setVerticalGroup(
            PIngresoTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PIngresoTelefono1Layout.createSequentialGroup()
                .addComponent(lblAgregarTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnModCel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Modificarp.png"))); // NOI18N
        btnModCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModCelActionPerformed(evt);
            }
        });

        tfMTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfMTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMTelefonoActionPerformed(evt);
            }
        });
        tfMTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfMTelefonoKeyTyped(evt);
            }
        });

        lblMTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblMTelefono.setText("Teléfono/Celular del empleado:");

        tTelefonos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tTelefonos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Teléfono"
            }
        ));
        tTelefonos.setFocusable(false);
        tTelefonos.getTableHeader().setReorderingAllowed(false);
        tTelefonos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tTelefonosMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tTelefonosMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tTelefonos);

        tfFiltro1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfFiltro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFiltro1ActionPerformed(evt);
            }
        });
        tfFiltro1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfFiltro1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFiltro1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFiltro1KeyTyped(evt);
            }
        });

        lblBusqTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBusqTel.setForeground(new java.awt.Color(255, 255, 255));
        lblBusqTel.setText("Buscar teléfono de:");

        lblPagar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPagar.setForeground(new java.awt.Color(255, 255, 255));
        lblPagar.setText("Otorgar pago a este empleado");
        lblPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPagarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PTelefono1Layout = new javax.swing.GroupLayout(PTelefono1);
        PTelefono1.setLayout(PTelefono1Layout);
        PTelefono1Layout.setHorizontalGroup(
            PTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTelefono1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PTelefono1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(btnModCel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliTel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(PTelefono1Layout.createSequentialGroup()
                        .addGroup(PTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBusqTel, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PTelefono1Layout.createSequentialGroup()
                        .addComponent(PIngresoTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))
                    .addComponent(lblPagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        PTelefono1Layout.setVerticalGroup(
            PTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTelefono1Layout.createSequentialGroup()
                .addGroup(PTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PTelefono1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblBusqTel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PTelefono1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnEliTel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnModCel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PTelefono1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PIngresoTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        btnEliEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminarp.png"))); // NOI18N
        btnEliEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliEmpleadoActionPerformed(evt);
            }
        });

        rbMRol.setBackground(new java.awt.Color(36, 41, 46));
        rbMRol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbMRol.setForeground(new java.awt.Color(255, 255, 255));
        rbMRol.setText("Rol");
        rbMRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMRolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfMNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblMSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblMDireccion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tfMSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfMDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(rbMRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addComponent(PTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnModEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(rbMRol)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnAgregarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agrega_empleado.png"))); // NOI18N
        btnAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEmpleadoActionPerformed(evt);
            }
        });

        rbActividad.setBackground(new java.awt.Color(36, 41, 46));
        rbActividad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbActividad.setForeground(new java.awt.Color(255, 255, 255));
        rbActividad.setText("En actividad");
        rbActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActividadActionPerformed(evt);
            }
        });

        rbTodos.setBackground(new java.awt.Color(36, 41, 46));
        rbTodos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbTodos.setForeground(new java.awt.Color(255, 255, 255));
        rbTodos.setText("En actividad y despedidos");
        rbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodosActionPerformed(evt);
            }
        });

        lblBusqLista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBusqLista.setForeground(new java.awt.Color(255, 255, 255));
        lblBusqLista.setText("Buscar empleados:");

        javax.swing.GroupLayout PEmpleadosLayout = new javax.swing.GroupLayout(PEmpleados);
        PEmpleados.setLayout(PEmpleadosLayout);
        PEmpleadosLayout.setHorizontalGroup(
            PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PEmpleadosLayout.createSequentialGroup()
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(PEmpleadosLayout.createSequentialGroup()
                                .addComponent(tfFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblBusqLista, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(rbActividad)
                                .addGap(28, 28, 28)
                                .addComponent(rbTodos)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(31, 31, 31))
                    .addGroup(PEmpleadosLayout.createSequentialGroup()
                        .addComponent(lblBusqEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(PEmpleadosLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PEmpleadosLayout.setVerticalGroup(
            PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PEmpleadosLayout.createSequentialGroup()
                .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PEmpleadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PEmpleadosLayout.createSequentialGroup()
                        .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PEmpleadosLayout.createSequentialGroup()
                                .addComponent(lblBusqEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addGroup(PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBusqLista, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbActividad)
                                .addComponent(rbTodos)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        lblDatos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDatos.setForeground(new java.awt.Color(255, 255, 255));
        lblDatos.setText("Agregar bono o descuento...");
        lblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDatosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(PEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3348, 3348, 3348)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(734, 734, 734)
                .addComponent(lblDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cargarInformacion(String contenido)
    {
        if (rbActividad.isSelected())
            cargarActivos(contenido);
        else
            cargarTodos(contenido);
    }
    
    private void cargarActivos(String contenido)
    {
        int fila = 0;
        try{
            Object O[] = null;
            List<entidades.Empleados> lista = clasEmpleados.buscarObjects(contenido, singleton.getConnection());
            for(int i = 0; i < lista.size(); i++)
            {
                if(!lista.get(i).getEstado().equals("Inactivo"))
                {
                    empleados.addRow(O);
                    empleados.setValueAt(lista.get(i).getId(), fila, 0);
                    empleados.setValueAt(lista.get(i).getNombre(), fila, 1);
                    empleados.setValueAt(lista.get(i).getApellido(), fila, 2);
                    empleados.setValueAt(lista.get(i).getDireccion(), fila, 3);
                    empleados.setValueAt(lista.get(i).getEstado(), fila, 4);
                    if (lista.get(i).getAdministrador() == 0)
                        empleados.setValueAt("Usuario", fila, 5);
                    else
                        empleados.setValueAt("Administrador", fila, 5);
                    empleados.setValueAt("Q. " + num.format(lista.get(i).getSalario()), fila, 6);
                    fila ++;
                }
            }
            tEmpleados.setModel(empleados);
            tfFiltro1.setEnabled(false);
            tfFiltro1.setText("");
            tfMTelefono.setEnabled(false);
            tfMTelefono.setText("");
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void cargarTodos(String contenido)
    {
        try{
            Object O[] = null;
            List<entidades.Empleados> lista = clasEmpleados.buscarObjects(contenido, singleton.getConnection());
            for(int i = 0; i < lista.size(); i++)
            {
                empleados.addRow(O);
                empleados.setValueAt(lista.get(i).getId(), i, 0);
                empleados.setValueAt(lista.get(i).getNombre(), i, 1);
                empleados.setValueAt(lista.get(i).getApellido(), i, 2);
                empleados.setValueAt(lista.get(i).getDireccion(), i, 3);
                empleados.setValueAt(lista.get(i).getEstado(), i, 4);
                if (lista.get(i).getAdministrador() == 0)
                    empleados.setValueAt("Usuario", i , 5);
                else
                    empleados.setValueAt("Administrador", i , 5);
                empleados.setValueAt("Q. " + num.format(lista.get(i).getSalario()), i , 6);
            }
            tEmpleados.setModel(empleados);
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void cargarTelefonos(String telefono)
    {
        try{
            Object O[] = null;
            List<entidades.Telefonos> lista = clasTelefonos.buscarObjects(idseleccionado, singleton.getConnection(), telefono);
            for(int i = 0; i < lista.size(); i++)
            {
                clientes.addRow(O);
                clientes.setValueAt(lista.get(i).getNumero(), i, 0);
            }
            tTelefonos.setModel(clientes);
        }catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    private void btnEliEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliEmpleadoActionPerformed
        if (empleado.getEstado().equals("Activo"))
            eliminarEmpleado();
        else
            recontratarEmpleado();
    }//GEN-LAST:event_btnEliEmpleadoActionPerformed
    
    private void insertarIcono(String ruta)
    {
        ImageIcon imagen = new ImageIcon(ruta);
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(btnEliEmpleado.getWidth(), btnEliEmpleado.getHeight(), Image.SCALE_DEFAULT));
        btnEliEmpleado.setIcon(icono);
    }
    
    private void eliminarEmpleado()
    {
        if (idseleccionado != -1)
        {
            if (empleado.getId() != 1)
            {
                if (JOptionPane.showConfirmDialog(null, "¿Está seguro de querer despedir este empleado?", "Aviso", 
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
                {
                    limpiarTablas();
                    empleado.setEstado("Inactivo");
                    empleado.setUsuario(null);
                    empleado.setContrasena(null);
                    clasEmpleados.editarObject(empleado, singleton.getConnection(), idseleccionado);
                    limpiarDespedir_Recontratar_yModificar();
                    cargarInformacion("");
                    JOptionPane.showMessageDialog(null, "Empleado despedido con éxito");
                }
            }
            else
                JOptionPane.showMessageDialog(null, "No se puede despedir al súper administrador");
        }
        else
            JOptionPane.showMessageDialog(null, "Por favor seleccione un empleado");
    }
    
    private void limpiarTEmpleados()
    {
        while(empleados.getRowCount()>0)
            empleados.removeRow(0);
    }
    private void limpiarTClientes()
    {
        while(clientes.getRowCount()>0)
            clientes.removeRow(0);
    }
    private void limpiarTablas()
    {
        while(empleados.getRowCount()>0)
            empleados.removeRow(0);
        while(clientes.getRowCount()>0)
            clientes.removeRow(0);
    }
    private void recontratarEmpleado()
    {
        if (idseleccionado != -1)
        {
            if (JOptionPane.showConfirmDialog(null, "¿Está seguro de querer recontratar este empleado?", "Aviso", 
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            {
                limpiarTablas();
                empleado.setEstado("Activo");
                clasEmpleados.editarObject(empleado, singleton.getConnection(), idseleccionado);
                limpiarDespedir_Recontratar_yModificar();
                cargarInformacion("");
                JOptionPane.showMessageDialog(null, "Empleado recontratado con éxito");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Por favor seleccione un empleado");
    }
    
    private void limpiarDespedir_Recontratar_yModificar()
    {
        tfMNombre.setText("");
        tfMApellidos.setText("");
        tfMDireccion.setText("");
        tfMSalario.setText("");
        tfFiltro.setText("");
        tfFiltro1.setText("");
        tfFiltro1.setEnabled(false);
        tfMTelefono.setText("");
        tfTelefono.setText("");
        tfTelefono.setEnabled(false);
        tfMTelefono.setEnabled(false);
        btnEliEmpleado.setEnabled(false);
        btnModEmpleado.setEnabled(false);
        btnTelefono.setEnabled(false);
        btnEliTel.setEnabled(false);
        btnModCel.setEnabled(false);
        tfMNombre.setEnabled(false);
        tfMApellidos.setEnabled(false);
        tfMDireccion.setEnabled(false);
        tfMSalario.setEnabled(false);
        rbMRol.setEnabled(false);
        rbMRol.setSelected(false);
        lblPagar.setEnabled(false);
        lblPagar.setVisible(false);
        lblBusqTel.setText("Buscar teléfono de:");
        lblMTelefono.setText("Teléfono/Celular de:");
        lblAgregarTelefono.setText("Agregar teléfono a:");
        seleccionado = -1;
        idseleccionado = -1;
    }
    
    private void tEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tEmpleadosMouseClicked

    }//GEN-LAST:event_tEmpleadosMouseClicked

    
    private void btnModEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModEmpleadoActionPerformed
        modificarEmpleado();
    }//GEN-LAST:event_btnModEmpleadoActionPerformed

    private void modificarEmpleado()
    {
        if (!tfMNombre.getText().equals("") && !tfMApellidos.getText().equals("") && !tfMDireccion.getText().equals("")
        && !tfMSalario.getText().equals(""))
        {
            if (JOptionPane.showConfirmDialog(null, "¿Está seguro de querer modificar los datos de este empleado?", "Aviso", 
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            {
                if (empleado.getId() == 1 && rbMRol.isSelected())
                    JOptionPane.showMessageDialog(null, "No se puede degradar al súper administrador");
                else
                {
                    empleado = clasEmpleados.obtenerEmpleado(singleton.getConnection(), idseleccionado);
                    limpiarTablas();
                    empleado.setId(idseleccionado);
                    empleado.setNombre(tfMNombre.getText());
                    empleado.setApellido(tfMApellidos.getText());
                    empleado.setDireccion(tfMDireccion.getText());
                    empleado.setSalario(Float.valueOf(tfMSalario.getText()));
                    if (rbMRol.isSelected())
                    {
                        if (empleado.getAdministrador() == 0)
                            empleado.setAdministrador((short)1);
                        else
                            empleado.setAdministrador((short)0);
                    }
                    clasEmpleados.editarObject(empleado, singleton.getConnection(), idseleccionado);
                    limpiarDespedir_Recontratar_yModificar();
                    JOptionPane.showMessageDialog(null, "Modificación exitosa");
                    cargarInformacion("");
                }
            }    
        }
        else
            JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos de modificación de un empleado.");
    }
    
    private void tfFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltroKeyTyped
        if (tfFiltro.getText().length() > 30) evt.consume();
        
    }//GEN-LAST:event_tfFiltroKeyTyped

    private void tfMNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMNombreKeyTyped
        char c = evt.getKeyChar();
        
        if ((c<'a' || c>'z') && (c<'A')|c>'Z')
        {
            if ((c != ' ') && (c != 'á') && (c != 'é') && (c != 'í') && (c != 'ó') && (c != 'ú'))
                evt.consume();
        }
        if (tfMNombre.getText().length() > 30) evt.consume();
    }//GEN-LAST:event_tfMNombreKeyTyped

    private void tfMApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMApellidosKeyTyped
        char c = evt.getKeyChar();
        
        if ((c<'a' || c>'z') && (c<'A')|c>'Z')
        {
            if ((c != ' ') && (c != 'á') && (c != 'é') && (c != 'í') && (c != 'ó') && (c != 'ú'))
                evt.consume();
        }
        if (tfMApellidos.getText().length() > 30) evt.consume();
    }//GEN-LAST:event_tfMApellidosKeyTyped

    private void tfMDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMDireccionKeyTyped
        if (tfMDireccion.getText().length() > 45) evt.consume();
    }//GEN-LAST:event_tfMDireccionKeyTyped

    private void tfFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltroKeyPressed
        
    }//GEN-LAST:event_tfFiltroKeyPressed

    private void tfFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltroKeyReleased
        limpiarTablas();
        limpiarTodo();
        cargarInformacion(tfFiltro.getText());
    }//GEN-LAST:event_tfFiltroKeyReleased

    private void tfMNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMNombreKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) tfMApellidos.requestFocus();
    }//GEN-LAST:event_tfMNombreKeyPressed

    private void tfMApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMApellidosKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) tfMDireccion.requestFocus();
    }//GEN-LAST:event_tfMApellidosKeyPressed

    private void tfMDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMDireccionKeyPressed
        
    }//GEN-LAST:event_tfMDireccionKeyPressed

    private void tEmpleadosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tEmpleadosMouseReleased
        if (evt.getButton() == 1)
            seleccionarEmpleado();
    }//GEN-LAST:event_tEmpleadosMouseReleased

    private void seleccionarEmpleado()
    {
        limpiarTClientes();
        int indice = tEmpleados.getSelectedRow() + 1;
        seleccionado = indice;
        idseleccionado = Integer.parseInt(String.valueOf(tEmpleados.getValueAt(tEmpleados.getSelectedRow(), 0)));
        TableModel modelo = tEmpleados.getModel();
        if (indice > 0)
        {
            empleado = clasEmpleados.obtenerEmpleado(singleton.getConnection(), idseleccionado);
            btnEliEmpleado.setEnabled(true);
            btnModEmpleado.setEnabled(true);
            btnTelefono.setEnabled(true);
            btnEliTel.setEnabled(false);
            btnModCel.setEnabled(false);
            tfMNombre.setEnabled(true);
            tfMApellidos.setEnabled(true);
            tfMDireccion.setEnabled(true);
            tfMSalario.setEnabled(true);
            tfFiltro1.setEnabled(true);
            rbMRol.setEnabled(true);
            if (empleado.getEstado().equals("Activo"))
            {
                lblPagar.setEnabled(true);
                lblPagar.setVisible(true);
            }
            else
            {
                lblPagar.setEnabled(false);
                lblPagar.setVisible(false);
            }
            tfFiltro1.setText("");
            tfMTelefono.setEnabled(false);
            tfMTelefono.setText("");
            tfMNombre.setText(empleado.getNombre());
            tfMApellidos.setText(empleado.getApellido());
            tfMSalario.setText(BigDecimal.valueOf(empleado.getSalario()).toString());
            tfMDireccion.setText(empleado.getDireccion());
            lblBusqTel.setText("Buscar teléfono de " + empleado.getNombre() + ":");
            lblMTelefono.setText("Teléfono/Celular de " + empleado.getNombre() + ":");
            lblAgregarTelefono.setText("Agregar teléfono a " + empleado.getNombre() + ":");
            tfTelefono.setEnabled(true);
            decidirImagen();
            obtenerRol();
            cargarTelefonos("");
        }
    }
    
    private void obtenerRol()
    {
        if (empleado.getAdministrador() == 0)
            rbMRol.setText("Ascender");
        else
            rbMRol.setText("Degradar");
    }
    
    private void decidirImagen()
    {
        if (empleado.getEstado().equals("Activo"))
            insertarIcono("src/main/resources/imagenes/Eliminarp.png");
        else
            insertarIcono("src/main/resources/imagenes/Agregarp.png");
    }
    
    private void tfMSalarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMSalarioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMSalarioKeyPressed

    private void tfMSalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMSalarioKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
        {
            if (c != '.')
                evt.consume();
        }
        if (tfMSalario.getText().length() > 6) evt.consume();
    }//GEN-LAST:event_tfMSalarioKeyTyped

    private void btnEliTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliTelActionPerformed
        eliminarTelefono();
    }//GEN-LAST:event_btnEliTelActionPerformed
    
    private void tTelefonosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTelefonosMouseClicked

    }//GEN-LAST:event_tTelefonosMouseClicked

    private void tTelefonosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTelefonosMouseReleased
        if (evt.getButton() == 1)
            seleccionarTelefono();
    }//GEN-LAST:event_tTelefonosMouseReleased
    
    private void seleccionarTelefono()
    {
        int indice = tTelefonos.getSelectedRow();
        seltel = indice;
        Telefonos telefono = clasTelefonos.obtenerTelefono(String.valueOf(tTelefonos.getValueAt(seltel, 0)), singleton.getConnection());
        tfMTelefono.setEnabled(true);
        tfMTelefono.setText(telefono.getNumero());
        TableModel modelo = tTelefonos.getModel();
        tfTelefono.setEnabled(true);
        if (indice > -1)
        {
            lblMTelefono.setEnabled(true);
            tfTelefono.setEnabled(true);
            btnModCel.setEnabled(true);
            btnEliTel.setEnabled(true);
        }
    }
    
    private void eliminarTelefono()
    {
        if (seltel > -1)
        {
            if (JOptionPane.showConfirmDialog(null, "¿Está seguro de querer eliminar el teléfono seleccionado de este empleado?", "Aviso", 
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            {
                Telefonos telefonos = clasTelefonos.obtenerTelefono(String.valueOf(tTelefonos.getValueAt(seltel, 0)), singleton.getConnection());
                clasTelefonos.eliminarTelefono(telefonos, singleton.getConnection());
                limpiarAlModificar_o_eliminarTel();
                JOptionPane.showMessageDialog(null, "Eliminación de celular exitosa");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Por favor seleccione un número de teléfono");
    }
    
    private void limpiarAlModificar_o_eliminarTel()
    {
        limpiarTClientes();
        cargarTelefonos("");
        tfMTelefono.setText("");
        tfMTelefono.setEnabled(false);
        tfFiltro1.setText("");
        btnModCel.setEnabled(false);
        btnEliTel.setEnabled(false);
        seltel = -1;
    }
    
    private void modificarTelefono()
    {
        if (!tfMTelefono.getText().equals(""))
        {
            if (tTelefonos.getSelectedRow() != -1)
            {
                List<entidades.Telefonos> resultado = clasTelefonos.existeTelefono(tfMTelefono.getText(), singleton.getConnection());
                if (resultado.isEmpty())
                {
                    if (JOptionPane.showConfirmDialog(null, "¿Está seguro de querer modificar el teléfono seleccionado de este empleado?", "Aviso", 
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
                    {
                        Telefonos telefono = clasTelefonos.obtenerTelefono(String.valueOf(tTelefonos.getValueAt(seltel, 0)), singleton.getConnection());
                        telefono.setNumero(tfMTelefono.getText());
                        clasTelefonos.editarTelefono(telefono, singleton.getConnection());
                        limpiarAlModificar_o_eliminarTel();
                        JOptionPane.showMessageDialog(null, "Modificación de celular exitosa");
                    }
                }
                else
                    JOptionPane.showMessageDialog(null, "El número de teléfono indicado para modificar ya existe\n"
                            + "en el empleado con código: " + resultado.get(0).getEmpleadosId());
            }
            else
                JOptionPane.showMessageDialog(null, "Por favor seleccione un número de teléfono");
        }
        else
            JOptionPane.showMessageDialog(null, "Por favor rellene el campo de teléfono celular");
    }
    
    private void btnModCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModCelActionPerformed
        modificarTelefono();
    }//GEN-LAST:event_btnModCelActionPerformed

    private void btnTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelefonoActionPerformed
        agregarTelefono();
    }//GEN-LAST:event_btnTelefonoActionPerformed

    private void agregarTelefono()
    {
        if (tfTelefono.getText().length() > 0)
        {
            if (tEmpleados.getSelectedRow() != -1)
            {
                List<entidades.Telefonos> resultado = clasTelefonos.existeTelefono(tfTelefono.getText(), singleton.getConnection());
                if (resultado.isEmpty())
                {
                    if (JOptionPane.showConfirmDialog(null, "¿Está seguro de querer agregarle un teléfono a este empleado?", "Aviso", 
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
                    {
                        Telefonos telefono = new Telefonos();
                        limpiarTClientes();
                        telefono.setNumero(tfTelefono.getText());
                        telefono.setEmpleadosId(idseleccionado);
                        clasTelefonos.registrarObject(telefono, singleton.getConnection());
                        tfTelefono.setText("");
                        tfMTelefono.setText("");
                        tfFiltro1.setText("");  
                        btnEliTel.setEnabled(false);
                        btnModCel.setEnabled(false);
                        cargarTelefonos("");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "El teléfono especificado ya existe\n"
                         + "en el empleado con código: " + resultado.get(0).getEmpleadosId());
                    tfTelefono.setText("");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Por favor seleccione un empleado");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Por favor rellene el campo que le solicita ingresar un telefono");
        }   
    }
    
    private void tfTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefonoKeyPressed
        //if (evt.getKeyCode()==KeyEvent.VK_ENTER) AgregarTelefono();
    }//GEN-LAST:event_tfTelefonoKeyPressed

    private void tfTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefonoKeyTyped
        char c = evt.getKeyChar();

        if ((c < '0' || c > '9') && (c != '+') && (c != ' ')) evt.consume();
        if (tfTelefono.getText().length() > 20) evt.consume();
    }//GEN-LAST:event_tfTelefonoKeyTyped

    private void tfFiltro1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltro1KeyPressed

    }//GEN-LAST:event_tfFiltro1KeyPressed

    private void tfFiltro1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltro1KeyReleased
        limpiarTClientes();
        if (tfFiltro1.getText().equals(""))
        {
            cargarTelefonos("");
            btnModCel.setEnabled(false);
            btnEliTel.setEnabled(false);
            tfMTelefono.setText("");
            tfMTelefono.setEnabled(false);
        }
        else
        {
            cargarTelefonos(tfFiltro1.getText());
            btnModCel.setEnabled(false);
            btnEliTel.setEnabled(false);
            tfMTelefono.setText("");
            tfMTelefono.setEnabled(false);
        }
            
    }//GEN-LAST:event_tfFiltro1KeyReleased

    private void tfFiltro1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFiltro1KeyTyped
        char c = evt.getKeyChar();

        if ((c < '0' || c > '9') && (c != '+') && (c != ' ')) evt.consume();
        if (tfFiltro.getText().length() > 10) evt.consume();
    }//GEN-LAST:event_tfFiltro1KeyTyped

    private void tfMTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMTelefonoKeyPressed
       // if (evt.getKeyCode()==KeyEvent.VK_ENTER) ModificarTelefono();
    }//GEN-LAST:event_tfMTelefonoKeyPressed

    private void tfMTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMTelefonoKeyTyped
        char c = evt.getKeyChar();

        if ((c < '0' || c > '9') && (c != '+') && (c != ' ')) evt.consume();
        if (tfMTelefono.getText().length() > 20) evt.consume();
    }//GEN-LAST:event_tfMTelefonoKeyTyped

    private void btnAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoActionPerformed
        FormAgregarEmpleado agregar  = new FormAgregarEmpleado();
        agregar.setSize(1010,600);
        agregar.setLocation(0, 0);
        this.removeAll();
        this.add(agregar,BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnAgregarEmpleadoActionPerformed

    private void rbActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActividadActionPerformed
        if (rbActividad.isSelected() && mostrartodosEmp == true)
        {
            rbTodos.setSelected(false);
            limpiarAlMostraryCargarInfo();
            mostrartodosEmp = false;
        }
        if (!rbActividad.isSelected())
            rbActividad.setSelected(true);
        
    }//GEN-LAST:event_rbActividadActionPerformed
    
    private void limpiarAlMostraryCargarInfo()
    {
        seleccionado = 0;
        idseleccionado = 0;
        seltel = 0;
        limpiarTodo();
        tfFiltro.setText("");
        limpiarTablas();
        cargarInformacion("");
    }
    
    private void rbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodosActionPerformed
        if (rbTodos.isSelected() && mostrartodosEmp == false)
        {
            rbActividad.setSelected(false);
            limpiarAlMostraryCargarInfo();
            mostrartodosEmp = true;
        }
        if (!rbTodos.isSelected())
            rbTodos.setSelected(true);
    }//GEN-LAST:event_rbTodosActionPerformed

    private void rbMRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMRolActionPerformed

    private void tfMTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMTelefonoActionPerformed

    private void tfFiltro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFiltro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFiltro1ActionPerformed

    private void tfMNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMNombreActionPerformed

    private void lblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDatosMouseClicked
        Bonos_YDescuentos agregar  = new Bonos_YDescuentos();
        agregar.setSize(1010,600);
        agregar.setLocation(0, 0);
        this.removeAll();
        this.add(agregar,BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_lblDatosMouseClicked

    private void lblPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPagarMouseClicked
        PagarEmpleados pagar = new PagarEmpleados(empleado);
        pagar.setSize(1010,600);
        pagar.setLocation(0, 0);
        this.removeAll();
        this.add(pagar,BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_lblPagarMouseClicked

    private void tEmpleadosMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tEmpleadosMouseDragged
        seleccionarEmpleado();
    }//GEN-LAST:event_tEmpleadosMouseDragged

    private void tEmpleadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tEmpleadosMousePressed

    }//GEN-LAST:event_tEmpleadosMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PEmpleados;
    private javax.swing.JPanel PIngresoTelefono1;
    private javax.swing.JPanel PTelefono1;
    private javax.swing.JButton btnAgregarEmpleado;
    private javax.swing.JButton btnEliEmpleado;
    private javax.swing.JButton btnEliTel;
    private javax.swing.JButton btnModCel;
    private javax.swing.JButton btnModEmpleado;
    private javax.swing.JButton btnTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAgregarTelefono;
    private javax.swing.JLabel lblBusqEmpleado;
    private javax.swing.JLabel lblBusqLista;
    private javax.swing.JLabel lblBusqTel;
    private javax.swing.JLabel lblDatos;
    private javax.swing.JLabel lblMApellidos;
    private javax.swing.JLabel lblMDireccion;
    private javax.swing.JLabel lblMNombre;
    private javax.swing.JLabel lblMSalario;
    private javax.swing.JLabel lblMTelefono;
    private javax.swing.JLabel lblPagar;
    private java.awt.Panel panel1;
    private javax.swing.JRadioButton rbActividad;
    private javax.swing.JRadioButton rbMRol;
    private javax.swing.JRadioButton rbTodos;
    private javax.swing.JTable tEmpleados;
    private javax.swing.JTable tTelefonos;
    private javax.swing.JTextField tfFiltro;
    private javax.swing.JTextField tfFiltro1;
    private javax.swing.JTextField tfMApellidos;
    private javax.swing.JTextField tfMDireccion;
    private javax.swing.JTextField tfMNombre;
    private javax.swing.JTextField tfMSalario;
    private javax.swing.JTextField tfMTelefono;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
