/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.awt.Color;

/**
 *
 * @author felipe
 */
public class fventa extends javax.swing.JPanel {

    /**
     * Creates new form fventa
     */
    public fventa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sepNombre = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sepDireccion = new javax.swing.JSeparator();
        txtDireccion = new javax.swing.JTextField();
        sepNit = new javax.swing.JSeparator();
        txtNit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFactura = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sepBuscar = new javax.swing.JSeparator();
        txtBuscar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sepDireccion1 = new javax.swing.JSeparator();
        txtDireccion1 = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 41, 46));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Datos del Cliente:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        sepNombre.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        add(sepNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 75, 267, 7));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Direccion:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        txtNombre.setBackground(new java.awt.Color(36, 41, 46));
        txtNombre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setAlignmentX(1.0F);
        txtNombre.setAlignmentY(1.0F);
        txtNombre.setBorder(null);
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 270, 36));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nit:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, -1, -1));

        sepDireccion.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        add(sepDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 75, 230, 7));

        txtDireccion.setBackground(new java.awt.Color(36, 41, 46));
        txtDireccion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion.setBorder(null);
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 230, 36));

        sepNit.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        add(sepNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 75, 190, 7));

        txtNit.setBackground(new java.awt.Color(36, 41, 46));
        txtNit.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNit.setForeground(new java.awt.Color(255, 255, 255));
        txtNit.setBorder(null);
        add(txtNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 190, 36));

        tbFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbFactura);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 630, 300));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Listado de productos");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buscar:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        sepBuscar.setBackground(new java.awt.Color(0, 136, 204));
        sepBuscar.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        add(sepBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 350, 4));

        txtBuscar.setBackground(new java.awt.Color(36, 41, 46));
        txtBuscar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscar.setAlignmentX(2.0F);
        txtBuscar.setAlignmentY(0.0F);
        txtBuscar.setBorder(null);
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 350, 36));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cantidad:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        sepDireccion1.setBackground(new java.awt.Color(0, 136, 204));
        sepDireccion1.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        add(sepDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 160, 7));

        txtDireccion1.setBackground(new java.awt.Color(36, 41, 46));
        txtDireccion1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDireccion1.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion1.setBorder(null);
        add(txtDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 160, 36));

        btnAceptar.setBackground(new java.awt.Color(0, 136, 204));
        btnAceptar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(null);
        btnAceptar.setFocusable(false);
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAceptarMouseExited(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 90, 50));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total a pagar");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Descuento:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseEntered
        // TODO add your handling code here:
        btnAceptar.setBackground(Color.red);
    }//GEN-LAST:event_btnAceptarMouseEntered

    private void btnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseExited
        // TODO add your handling code here:
          btnAceptar.setBackground(new Color(0, 136, 204));
    }//GEN-LAST:event_btnAceptarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator sepBuscar;
    private javax.swing.JSeparator sepDireccion;
    private javax.swing.JSeparator sepDireccion1;
    private javax.swing.JSeparator sepNit;
    private javax.swing.JSeparator sepNombre;
    private javax.swing.JTable tbFactura;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccion1;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
