/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import entidades.Empleados;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import recursoshumanos.ClaseEmpleados;
import singleton.singleton;

/**
 *
 * @author igeni
 */
public class Inicio extends javax.swing.JFrame {

    ClaseEmpleados clasEmpleados = new ClaseEmpleados();//Variable que va a permitir la adición del nuevo administrador a la empresa
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        tfNombres.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTNInsertar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfNombres = new javax.swing.JTextField();
        tfApellidos = new javax.swing.JTextField();
        tfDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfSalario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(961, 330));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(36, 41, 46));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPanel1KeyTyped(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cont1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 360, 240));

        BTNInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar1.png"))); // NOI18N
        BTNInsertar.setBorder(null);
        BTNInsertar.setBorderPainted(false);
        BTNInsertar.setContentAreaFilled(false);
        BTNInsertar.setFocusPainted(false);
        BTNInsertar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTNInsertar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar3.png"))); // NOI18N
        BTNInsertar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar2.png"))); // NOI18N
        BTNInsertar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BTNInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNInsertarActionPerformed(evt);
            }
        });
        jPanel1.add(BTNInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida2.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida3.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida1.png"))); // NOI18N
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimiza2.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimizar3.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimizar1.png"))); // NOI18N
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hola, usted será el nuevo administrador.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        tfNombres.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNombresKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombresKeyTyped(evt);
            }
        });
        jPanel1.add(tfNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 200, -1));

        tfApellidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfApellidosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfApellidosKeyTyped(evt);
            }
        });
        jPanel1.add(tfApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 200, -1));

        tfDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDireccionKeyTyped(evt);
            }
        });
        jPanel1.add(tfDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Proceda a ingresar sus datos personales:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mis nombres son:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mis apellidos son:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mi salario será de:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Yo vivo en:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        tfSalario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSalarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSalarioKeyTyped(evt);
            }
        });
        jPanel1.add(tfSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1031, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Minimizar el form
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setState(Inicio.ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed
    //Preguntar si se va a salir del programa
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int sino = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(null,"¿Desea Salir del Sistema?","Exit",sino);
        if(resultado==0){

            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    //Insertar al administrador
    private void BTNInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNInsertarActionPerformed
        Insertar();
    }//GEN-LAST:event_BTNInsertarActionPerformed
    //Insertar al administrador
    private void Insertar()
    {
        if (tfNombres.getText().length() > 0 && tfApellidos.getText().length() > 0 && tfDireccion.getText().length() > 0
                && tfSalario.getText().length() > 0)
        {
            if (JOptionPane.showConfirmDialog(null, "Asegúrese de que los datos estén correctamente escritos\nSi sí, "
                    + "por favor haga click en el botón sí.", "Aviso", 
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            {
                Empleados empleado = new Empleados();
                empleado.setNombre(tfNombres.getText());
                empleado.setApellido(tfApellidos.getText());
                empleado.setDireccion(tfDireccion.getText());
                empleado.setSalario(Float.valueOf(tfSalario.getText()));
                empleado.setAdministrador((short)1);
                empleado.setEstado("Activo");
                clasEmpleados.registrarObject(empleado, singleton.getConnection());
                CreacionUsuarios crear = new CreacionUsuarios();
                this.setVisible(false);
                crear.empleado = empleado;
                crear.setVisible(true);
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos");
    }
    private void jPanel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyTyped

    }//GEN-LAST:event_jPanel1KeyTyped
    //Validar un máximo de 30 caracteres en el campo de nombre, validando así mismo sólo el uso de las letras del abecedario
    //Con sus letras tildadas, y letras mayúsculas
    private void tfNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombresKeyTyped
        char c = evt.getKeyChar();
        
        if ((c<'a' || c>'z') && (c<'A')|c>'Z')
        {
            if ((c != ' ') && (c != 'á') && (c != 'é') && (c != 'í') && (c != 'ó') && (c != 'ú'))
                evt.consume();
        }
        if (tfNombres.getText().length() > 30) evt.consume();
    }//GEN-LAST:event_tfNombresKeyTyped
    //Validar un máximo de 30 caracteres en el campo de apellido, validando así mismo sólo el uso de las letras del abecedario
    //Con sus letras tildadas, y letras mayúsculas
    private void tfApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApellidosKeyTyped
        char c = evt.getKeyChar();
        
        if ((c<'a' || c>'z') && (c<'A')|c>'Z')
        {
            if ((c != ' ') && (c != 'á') && (c != 'é') && (c != 'í') && (c != 'ó') && (c != 'ú'))
                evt.consume();
        }
        if (tfApellidos.getText().length() > 30) evt.consume();
    }//GEN-LAST:event_tfApellidosKeyTyped
    //Validar un máximo de 45 caracteres en el campo de dirección
    private void tfDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDireccionKeyTyped
        char c = evt.getKeyChar();
        if (tfDireccion.getText().length() > 45) evt.consume();
    }//GEN-LAST:event_tfDireccionKeyTyped
    //Validar movimiento entre campos de texto
    private void tfNombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombresKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
            tfApellidos.requestFocus();
        if (evt.getKeyCode()== KeyEvent.VK_UP)
            tfSalario.requestFocus();
        if (evt.getKeyCode()== KeyEvent.VK_DOWN)
            tfApellidos.requestFocus();
    }//GEN-LAST:event_tfNombresKeyPressed
    //Validar movimiento entre campos de texto
    private void tfApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApellidosKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
            tfDireccion.requestFocus();
        if (evt.getKeyCode()== KeyEvent.VK_UP)
            tfNombres.requestFocus();
        if (evt.getKeyCode()== KeyEvent.VK_DOWN)
            tfDireccion.requestFocus();
    }//GEN-LAST:event_tfApellidosKeyPressed
    //Validar movimiento entre campos de texto
    private void tfDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDireccionKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
            tfSalario.requestFocus();
        if (evt.getKeyCode()== KeyEvent.VK_UP)
            tfApellidos.requestFocus();
        if (evt.getKeyCode()== KeyEvent.VK_DOWN)
            tfSalario.requestFocus();
    }//GEN-LAST:event_tfDireccionKeyPressed
    //Validar movimiento entre campos de texto
    private void tfSalarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSalarioKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
            Insertar();
        if (evt.getKeyCode()== KeyEvent.VK_UP)
            tfDireccion.requestFocus();
        if (evt.getKeyCode()== KeyEvent.VK_DOWN)
            tfNombres.requestFocus();
    }//GEN-LAST:event_tfSalarioKeyPressed
    //Validación de un máximo de 6 caracteres en el campo de salario, con dígitos validados y el punto flotante
    private void tfSalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSalarioKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
        {
            if (c != '.')
                evt.consume();
        }
        if (tfSalario.getText().length() > 6) evt.consume();
    }//GEN-LAST:event_tfSalarioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNInsertar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfNombres;
    private javax.swing.JTextField tfSalario;
    // End of variables declaration//GEN-END:variables
}
