/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

//import Clases.InsertarEmpleado;
import recursoshumanos.Contrasena;
import recursoshumanos.ClaseEmpleados;
import entidades.Empleados;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import singleton.singleton;
import state.Autenticacion;
import state.Comportamiento;

/**
 *
 * @author Hp
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Empleados empleado = null;//Variable que se va a usar para el traspaso de los datos de un empleado, al recuperar o crear una cuenta
    ClaseEmpleados clasEmpleados = new ClaseEmpleados();//Variable que va a permitir la validación de usuario y contraseña
    Contrasena contrasena = new Contrasena();//Variable que se usa para desencriptar la contraseña
    //Se valida si existe el súper administrador, si sí, se muestra un login, si no, se le piden los datos para ingresar
    public Login() {
        if (clasEmpleados.buscarObjects("", singleton.getConnection()).isEmpty())
        {
            Inicio crear = new Inicio();
            crear.setVisible(true);
            this.setVisible(false);
        }
        initComponents();
        tfUsuario.requestFocus();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        pfContrasena = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        btnRespaldo = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 41, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cont1.png"))); // NOI18N
        jPanel1.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 380, 250));

        lblContrasena.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasena.setText("Contraseña:");
        jPanel1.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario:");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, -1, -1));

        tfUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(tfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 210, -1));

        pfContrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pfContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfContrasenaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pfContrasenaKeyTyped(evt);
            }
        });
        jPanel1.add(pfContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 210, -1));

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar1.png"))); // NOI18N
        btnIngresar.setBorder(null);
        btnIngresar.setBorderPainted(false);
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.setFocusPainted(false);
        btnIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar3.png"))); // NOI18N
        btnIngresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar2.png"))); // NOI18N
        btnIngresar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida2.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setFocusPainted(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida3.png"))); // NOI18N
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida1.png"))); // NOI18N
        btnSalir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimiza2.png"))); // NOI18N
        btnMinimizar.setBorder(null);
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setFocusPainted(false);
        btnMinimizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinimizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimizar3.png"))); // NOI18N
        btnMinimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimizar1.png"))); // NOI18N
        btnMinimizar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, -1, -1));

        btnRespaldo.setBackground(new java.awt.Color(36, 41, 46));
        btnRespaldo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnRespaldo.setForeground(new java.awt.Color(255, 255, 255));
        btnRespaldo.setText("No recuerdo mi contraseña...");
        btnRespaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespaldoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRespaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        btnCrear.setBackground(new java.awt.Color(36, 41, 46));
        btnCrear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Soy nuevo en la empresa...");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Botón de salir
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int sino = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(null,"¿Desea Sallir del Sistema?","Exit",sino);
        if(resultado==0){
            
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed
    //Botón de minimizar
    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setState(fgeneral.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed
    //Entrar al programa
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
         Loguear();
    }//GEN-LAST:event_btnIngresarActionPerformed
    //Entrar al programa
    private void Loguear()
    {
        try {
            if (tfUsuario.getText().length() == 0 || pfContrasena.getPassword().length == 0)
                JOptionPane.showMessageDialog(null, "Por favor rellene los campos de usuario y contraseña");
            else
            {
                empleado = clasEmpleados.buscarUsuario(singleton.getConnection(), tfUsuario.getText());
                if (empleado != null)
                {
                    Comportamiento comportamiento = new Comportamiento();
                    Autenticacion autenticacion = new Autenticacion();
                    autenticacion.setContrasena(String.valueOf(pfContrasena.getPassword()));
                    comportamiento.setEstado(autenticacion);
                    if (comportamiento.ejecutarEstado(empleado))
                    {
                        fgeneral aplicacion = new fgeneral();
                        aplicacion.empleado = this.empleado;
                        aplicacion.setVisible(true);
                        this.setVisible(false);
                    }
                    else
                        JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos");
                }
                else
                    JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos");
            }
        } catch (Exception ex) {
           Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    //Validación de un máximo de 25 caracteres para ingresar al usuario
    private void tfUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUsuarioKeyTyped
        int maximo = 25;
        if (tfUsuario.getText().length()>= maximo)
            evt.consume();
    }//GEN-LAST:event_tfUsuarioKeyTyped
    //Validación de un máximo de 30 caracteres para ingresar la contraseña
    private void pfContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfContrasenaKeyTyped
        int maximo = 30;
        if (pfContrasena.getPassword().length>= maximo)
            evt.consume();
    }//GEN-LAST:event_pfContrasenaKeyTyped
    //Eliminar el componente (form) de login si no existe el súper administrador, para mantener activo sólo el form de inicio
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (clasEmpleados.buscarObjects("", singleton.getConnection()).isEmpty())
            this.dispose();
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

   //Movimiento entre campos de texto
    private void tfUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUsuarioKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
            pfContrasena.requestFocus();
    }//GEN-LAST:event_tfUsuarioKeyPressed
    //Ingresar al programa haciendo enter, luego de tener usuario y contraseña, en el campo contraseña
    private void pfContrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfContrasenaKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
            Loguear();
    }//GEN-LAST:event_pfContrasenaKeyPressed

    private void btnRespaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespaldoActionPerformed
        String respuesta = JOptionPane.showInputDialog("¿Usuario?");
        if (respuesta != null)
        {
            if (!respuesta.equals(""))
            {
                empleado = clasEmpleados.buscarUsuario(singleton.getConnection(), respuesta);
                if (empleado != null) {
                    RespaldoCuenta recuperar = new RespaldoCuenta();
                    recuperar.setVisible(true);
                    recuperar.empleado = this.empleado;
                    this.setVisible(false);
                } else
                    JOptionPane.showMessageDialog(null, "El usuario especificado no existe");
            }
            else
                JOptionPane.showMessageDialog(null, "Por favor rellene el campo solicitado");
        }
    }//GEN-LAST:event_btnRespaldoActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String respuesta = JOptionPane.showInputDialog("¿Código de usuario?");
        try{
            if (respuesta != null) {
                if (!respuesta.equals("")) {
                    empleado = clasEmpleados.obtenerEmpleado(singleton.getConnection(), Integer.parseInt(respuesta));
                    if (empleado != null) {
                        if (empleado.getUsuario() == null) {
                            CreacionUsuarios crear = new CreacionUsuarios();
                            crear.empleado = this.empleado;
                            crear.setVisible(true);
                            this.setVisible(false);
                        } else {
                            JOptionPane.showMessageDialog(null, "Este código ya tiene un usuario creado");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El código introducido no existe");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor rellene el campo solicitado");
                }
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ingrese sólo dígitos del 0 al 9");
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton btnRespaldo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField pfContrasena;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
