/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

//import Clases.InsertarEmpleado;
import recursoshumanos.Contrasena;
import recursoshumanos.ClaseEmpleados;
import entidades.Empleados;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import singleton.singleton;

/**
 *
 * @author Hp
 */
public class RespaldoCuenta extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Empleados empleado = null;
    Contrasena contrasena = new Contrasena();
    ClaseEmpleados clasEmpleados = new ClaseEmpleados();
    public RespaldoCuenta() {
        initComponents();
        this.setLocationRelativeTo(null);
        pfContrasena.setEnabled(false);
        pfConfirmarContra.setEnabled(false);
        btnNuevaContra.setEnabled(true);
        pfContrasena.setVisible(false);
        pfConfirmarContra.setVisible(false);
        btnNuevaContra.setVisible(false);
        lblContrasena.setVisible(false);
        lblConfirmarContra.setVisible(false);
        tfRespuesta.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnRespuesta = new javax.swing.JButton();
        pfConfirmarContra = new javax.swing.JPasswordField();
        lblConfirmarContra = new javax.swing.JLabel();
        btnNuevaContra = new javax.swing.JButton();
        lblPregunta = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        pfContrasena = new javax.swing.JPasswordField();
        tfRespuesta = new javax.swing.JTextField();
        lblRespuesta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 41, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida2.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salida3.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida1.png"))); // NOI18N
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimiza2.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimizar3.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimizar1.png"))); // NOI18N
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, -1, -1));

        btnRespuesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar1.png"))); // NOI18N
        btnRespuesta.setBorder(null);
        btnRespuesta.setBorderPainted(false);
        btnRespuesta.setContentAreaFilled(false);
        btnRespuesta.setFocusPainted(false);
        btnRespuesta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRespuesta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar3.png"))); // NOI18N
        btnRespuesta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar2.png"))); // NOI18N
        btnRespuesta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuestaActionPerformed(evt);
            }
        });
        jPanel1.add(btnRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        pfConfirmarContra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pfConfirmarContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfConfirmarContraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pfConfirmarContraKeyTyped(evt);
            }
        });
        jPanel1.add(pfConfirmarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 210, -1));

        lblConfirmarContra.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblConfirmarContra.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmarContra.setText("Confirmar contraseña:");
        jPanel1.add(lblConfirmarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        btnNuevaContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar1.png"))); // NOI18N
        btnNuevaContra.setBorder(null);
        btnNuevaContra.setBorderPainted(false);
        btnNuevaContra.setContentAreaFilled(false);
        btnNuevaContra.setFocusPainted(false);
        btnNuevaContra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevaContra.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar3.png"))); // NOI18N
        btnNuevaContra.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ingresar2.png"))); // NOI18N
        btnNuevaContra.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnNuevaContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaContraActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevaContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));

        lblPregunta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPregunta.setForeground(new java.awt.Color(255, 255, 255));
        lblPregunta.setText("Pregunta:");
        jPanel1.add(lblPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        lblContrasena.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasena.setText("Nueva contraseña:");
        jPanel1.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        pfContrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pfContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfContrasenaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pfContrasenaKeyTyped(evt);
            }
        });
        jPanel1.add(pfContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 210, -1));

        tfRespuesta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfRespuesta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfRespuestaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfRespuestaKeyTyped(evt);
            }
        });
        jPanel1.add(tfRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 210, -1));

        lblRespuesta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        lblRespuesta.setText("Respuesta:");
        jPanel1.add(lblRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int sino = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(null,"¿Desea Sallir del Sistema?","Exit",sino);
        if(resultado==0){
            
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         //this.setState(General.ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lblUsuario.setText("Empleado: " + empleado.getNombre() + " " + empleado.getApellido());
        lblPregunta.setText(empleado.getPregunta());
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btnRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestaActionPerformed
        validarRespuesta();
    }//GEN-LAST:event_btnRespuestaActionPerformed

    private void validarRespuesta()
    {
        if (tfRespuesta.getText().equals(empleado.getRespuesta()))
        {
            lblContrasena.setVisible(true);
            lblConfirmarContra.setVisible(true);
            pfContrasena.setVisible(true);
            pfContrasena.setEnabled(true);
            pfConfirmarContra.setVisible(true);
            pfConfirmarContra.setEnabled(true);
            btnNuevaContra.setEnabled(true);
            btnNuevaContra.setVisible(true);
            tfRespuesta.setEnabled(false);
            tfRespuesta.setText("");
            btnRespuesta.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Proceda a rellenar los siguientes campos para recuperar su cuenta");
            pfContrasena.requestFocus();
        }
        else
            JOptionPane.showMessageDialog(null, "Respuesta incorrecta");
    }
    private void pfConfirmarContraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfConfirmarContraKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) generarNuevaContrasena();
    }//GEN-LAST:event_pfConfirmarContraKeyPressed

    private void pfConfirmarContraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfConfirmarContraKeyTyped
        if (pfConfirmarContra.getPassword().length > 25) evt.consume();
        if (evt.getKeyCode()==KeyEvent.VK_UP || evt.getKeyCode()==KeyEvent.VK_DOWN) pfContrasena.requestFocus();
    }//GEN-LAST:event_pfConfirmarContraKeyTyped

    private void btnNuevaContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaContraActionPerformed
        generarNuevaContrasena();
    }//GEN-LAST:event_btnNuevaContraActionPerformed

    private void generarNuevaContrasena()
    {
        if (String.valueOf(pfContrasena.getPassword()).equals(String.valueOf(pfConfirmarContra.getPassword())))
        {
            JOptionPane.showMessageDialog(null, "Nueva contraseña ingresada con éxito");
            empleado.setContrasena(contrasena.Encriptar(String.valueOf(pfContrasena.getPassword())));
            clasEmpleados.editarObject(empleado, singleton.getConnection(), empleado.getId());
            Login login = new Login();
            login.setVisible(true);
            this.setVisible(false);
        }
        else
            JOptionPane.showMessageDialog(null, "Las contraseñas ingresadas no coinciden");
    }
    private void pfContrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfContrasenaKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) pfConfirmarContra.requestFocus();
        if (evt.getKeyCode()==KeyEvent.VK_UP || evt.getKeyCode()==KeyEvent.VK_DOWN) pfConfirmarContra.requestFocus();
    }//GEN-LAST:event_pfContrasenaKeyPressed

    private void pfContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfContrasenaKeyTyped
        if (pfContrasena.getPassword().length > 25) evt.consume();
    }//GEN-LAST:event_pfContrasenaKeyTyped

    private void tfRespuestaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRespuestaKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) validarRespuesta();
    }//GEN-LAST:event_tfRespuestaKeyPressed

    private void tfRespuestaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRespuestaKeyTyped
        if (tfRespuesta.getText().length() > 60) evt.consume();
    }//GEN-LAST:event_tfRespuestaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RespaldoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RespaldoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RespaldoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RespaldoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RespaldoCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevaContra;
    private javax.swing.JButton btnRespuesta;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfirmarContra;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField pfConfirmarContra;
    private javax.swing.JPasswordField pfContrasena;
    private javax.swing.JTextField tfRespuesta;
    // End of variables declaration//GEN-END:variables
}
